// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devices.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/freifunkMUC/wg-access-server/proto/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DevicesName is the fully-qualified name of the Devices service.
	DevicesName = "proto.Devices"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DevicesAddDeviceProcedure is the fully-qualified name of the Devices's AddDevice RPC.
	DevicesAddDeviceProcedure = "/proto.Devices/AddDevice"
	// DevicesListDevicesProcedure is the fully-qualified name of the Devices's ListDevices RPC.
	DevicesListDevicesProcedure = "/proto.Devices/ListDevices"
	// DevicesDeleteDeviceProcedure is the fully-qualified name of the Devices's DeleteDevice RPC.
	DevicesDeleteDeviceProcedure = "/proto.Devices/DeleteDevice"
	// DevicesRenameDeviceProcedure is the fully-qualified name of the Devices's RenameDevice RPC.
	DevicesRenameDeviceProcedure = "/proto.Devices/RenameDevice"
	// DevicesRotateDeviceKeyProcedure is the fully-qualified name of the Devices's RotateDeviceKey RPC.
	DevicesRotateDeviceKeyProcedure = "/proto.Devices/RotateDeviceKey"
	// DevicesListAllDevicesProcedure is the fully-qualified name of the Devices's ListAllDevices RPC.
	DevicesListAllDevicesProcedure = "/proto.Devices/ListAllDevices"
	// DevicesSetDeviceAccessProcedure is the fully-qualified name of the Devices's SetDeviceAccess RPC.
	DevicesSetDeviceAccessProcedure = "/proto.Devices/SetDeviceAccess"
	// DevicesSetDeviceRoutesProcedure is the fully-qualified name of the Devices's SetDeviceRoutes RPC.
	DevicesSetDeviceRoutesProcedure = "/proto.Devices/SetDeviceRoutes"
)

// DevicesClient is a client for the proto.Devices service.
type DevicesClient interface {
	AddDevice(context.Context, *connect.Request[proto.AddDeviceReq]) (*connect.Response[proto.Device], error)
	ListDevices(context.Context, *connect.Request[proto.ListDevicesReq]) (*connect.Response[proto.ListDevicesRes], error)
	DeleteDevice(context.Context, *connect.Request[proto.DeleteDeviceReq]) (*connect.Response[emptypb.Empty], error)
	RenameDevice(context.Context, *connect.Request[proto.RenameDeviceReq]) (*connect.Response[proto.Device], error)
	// RotateDeviceKey replaces the key material of one of your own devices,
	// keeping its name, address and everything else. Your own only, and
	// deliberately so: whoever rotates a key holds the private half, and that
	// is the person using the device, not an admin.
	RotateDeviceKey(context.Context, *connect.Request[proto.RotateDeviceKeyReq]) (*connect.Response[proto.Device], error)
	// admin only
	ListAllDevices(context.Context, *connect.Request[proto.ListAllDevicesReq]) (*connect.Response[proto.ListAllDevicesRes], error)
	// SetDeviceAccess blocks a device from connecting, or gives it an expiry
	// date. It is admin only: a user must not be able to lift a block or
	// extend the expiry an admin set on their device.
	SetDeviceAccess(context.Context, *connect.Request[proto.SetDeviceAccessReq]) (*connect.Response[proto.Device], error)
	// SetDeviceRoutes sets the networks that live behind a device, which is what
	// makes it a site-to-site link or a subnet router. Admin only: a user who
	// could claim a network would be claiming everybody's traffic to it.
	SetDeviceRoutes(context.Context, *connect.Request[proto.SetDeviceRoutesReq]) (*connect.Response[proto.Device], error)
}

// NewDevicesClient constructs a client for the proto.Devices service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDevicesClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DevicesClient {
	baseURL = strings.TrimRight(baseURL, "/")
	devicesMethods := proto.File_devices_proto.Services().ByName("Devices").Methods()
	return &devicesClient{
		addDevice: connect.NewClient[proto.AddDeviceReq, proto.Device](
			httpClient,
			baseURL+DevicesAddDeviceProcedure,
			connect.WithSchema(devicesMethods.ByName("AddDevice")),
			connect.WithClientOptions(opts...),
		),
		listDevices: connect.NewClient[proto.ListDevicesReq, proto.ListDevicesRes](
			httpClient,
			baseURL+DevicesListDevicesProcedure,
			connect.WithSchema(devicesMethods.ByName("ListDevices")),
			connect.WithClientOptions(opts...),
		),
		deleteDevice: connect.NewClient[proto.DeleteDeviceReq, emptypb.Empty](
			httpClient,
			baseURL+DevicesDeleteDeviceProcedure,
			connect.WithSchema(devicesMethods.ByName("DeleteDevice")),
			connect.WithClientOptions(opts...),
		),
		renameDevice: connect.NewClient[proto.RenameDeviceReq, proto.Device](
			httpClient,
			baseURL+DevicesRenameDeviceProcedure,
			connect.WithSchema(devicesMethods.ByName("RenameDevice")),
			connect.WithClientOptions(opts...),
		),
		rotateDeviceKey: connect.NewClient[proto.RotateDeviceKeyReq, proto.Device](
			httpClient,
			baseURL+DevicesRotateDeviceKeyProcedure,
			connect.WithSchema(devicesMethods.ByName("RotateDeviceKey")),
			connect.WithClientOptions(opts...),
		),
		listAllDevices: connect.NewClient[proto.ListAllDevicesReq, proto.ListAllDevicesRes](
			httpClient,
			baseURL+DevicesListAllDevicesProcedure,
			connect.WithSchema(devicesMethods.ByName("ListAllDevices")),
			connect.WithClientOptions(opts...),
		),
		setDeviceAccess: connect.NewClient[proto.SetDeviceAccessReq, proto.Device](
			httpClient,
			baseURL+DevicesSetDeviceAccessProcedure,
			connect.WithSchema(devicesMethods.ByName("SetDeviceAccess")),
			connect.WithClientOptions(opts...),
		),
		setDeviceRoutes: connect.NewClient[proto.SetDeviceRoutesReq, proto.Device](
			httpClient,
			baseURL+DevicesSetDeviceRoutesProcedure,
			connect.WithSchema(devicesMethods.ByName("SetDeviceRoutes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// devicesClient implements DevicesClient.
type devicesClient struct {
	addDevice       *connect.Client[proto.AddDeviceReq, proto.Device]
	listDevices     *connect.Client[proto.ListDevicesReq, proto.ListDevicesRes]
	deleteDevice    *connect.Client[proto.DeleteDeviceReq, emptypb.Empty]
	renameDevice    *connect.Client[proto.RenameDeviceReq, proto.Device]
	rotateDeviceKey *connect.Client[proto.RotateDeviceKeyReq, proto.Device]
	listAllDevices  *connect.Client[proto.ListAllDevicesReq, proto.ListAllDevicesRes]
	setDeviceAccess *connect.Client[proto.SetDeviceAccessReq, proto.Device]
	setDeviceRoutes *connect.Client[proto.SetDeviceRoutesReq, proto.Device]
}

// AddDevice calls proto.Devices.AddDevice.
func (c *devicesClient) AddDevice(ctx context.Context, req *connect.Request[proto.AddDeviceReq]) (*connect.Response[proto.Device], error) {
	return c.addDevice.CallUnary(ctx, req)
}

// ListDevices calls proto.Devices.ListDevices.
func (c *devicesClient) ListDevices(ctx context.Context, req *connect.Request[proto.ListDevicesReq]) (*connect.Response[proto.ListDevicesRes], error) {
	return c.listDevices.CallUnary(ctx, req)
}

// DeleteDevice calls proto.Devices.DeleteDevice.
func (c *devicesClient) DeleteDevice(ctx context.Context, req *connect.Request[proto.DeleteDeviceReq]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteDevice.CallUnary(ctx, req)
}

// RenameDevice calls proto.Devices.RenameDevice.
func (c *devicesClient) RenameDevice(ctx context.Context, req *connect.Request[proto.RenameDeviceReq]) (*connect.Response[proto.Device], error) {
	return c.renameDevice.CallUnary(ctx, req)
}

// RotateDeviceKey calls proto.Devices.RotateDeviceKey.
func (c *devicesClient) RotateDeviceKey(ctx context.Context, req *connect.Request[proto.RotateDeviceKeyReq]) (*connect.Response[proto.Device], error) {
	return c.rotateDeviceKey.CallUnary(ctx, req)
}

// ListAllDevices calls proto.Devices.ListAllDevices.
func (c *devicesClient) ListAllDevices(ctx context.Context, req *connect.Request[proto.ListAllDevicesReq]) (*connect.Response[proto.ListAllDevicesRes], error) {
	return c.listAllDevices.CallUnary(ctx, req)
}

// SetDeviceAccess calls proto.Devices.SetDeviceAccess.
func (c *devicesClient) SetDeviceAccess(ctx context.Context, req *connect.Request[proto.SetDeviceAccessReq]) (*connect.Response[proto.Device], error) {
	return c.setDeviceAccess.CallUnary(ctx, req)
}

// SetDeviceRoutes calls proto.Devices.SetDeviceRoutes.
func (c *devicesClient) SetDeviceRoutes(ctx context.Context, req *connect.Request[proto.SetDeviceRoutesReq]) (*connect.Response[proto.Device], error) {
	return c.setDeviceRoutes.CallUnary(ctx, req)
}

// DevicesHandler is an implementation of the proto.Devices service.
type DevicesHandler interface {
	AddDevice(context.Context, *connect.Request[proto.AddDeviceReq]) (*connect.Response[proto.Device], error)
	ListDevices(context.Context, *connect.Request[proto.ListDevicesReq]) (*connect.Response[proto.ListDevicesRes], error)
	DeleteDevice(context.Context, *connect.Request[proto.DeleteDeviceReq]) (*connect.Response[emptypb.Empty], error)
	RenameDevice(context.Context, *connect.Request[proto.RenameDeviceReq]) (*connect.Response[proto.Device], error)
	// RotateDeviceKey replaces the key material of one of your own devices,
	// keeping its name, address and everything else. Your own only, and
	// deliberately so: whoever rotates a key holds the private half, and that
	// is the person using the device, not an admin.
	RotateDeviceKey(context.Context, *connect.Request[proto.RotateDeviceKeyReq]) (*connect.Response[proto.Device], error)
	// admin only
	ListAllDevices(context.Context, *connect.Request[proto.ListAllDevicesReq]) (*connect.Response[proto.ListAllDevicesRes], error)
	// SetDeviceAccess blocks a device from connecting, or gives it an expiry
	// date. It is admin only: a user must not be able to lift a block or
	// extend the expiry an admin set on their device.
	SetDeviceAccess(context.Context, *connect.Request[proto.SetDeviceAccessReq]) (*connect.Response[proto.Device], error)
	// SetDeviceRoutes sets the networks that live behind a device, which is what
	// makes it a site-to-site link or a subnet router. Admin only: a user who
	// could claim a network would be claiming everybody's traffic to it.
	SetDeviceRoutes(context.Context, *connect.Request[proto.SetDeviceRoutesReq]) (*connect.Response[proto.Device], error)
}

// NewDevicesHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDevicesHandler(svc DevicesHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	devicesMethods := proto.File_devices_proto.Services().ByName("Devices").Methods()
	devicesAddDeviceHandler := connect.NewUnaryHandler(
		DevicesAddDeviceProcedure,
		svc.AddDevice,
		connect.WithSchema(devicesMethods.ByName("AddDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesListDevicesHandler := connect.NewUnaryHandler(
		DevicesListDevicesProcedure,
		svc.ListDevices,
		connect.WithSchema(devicesMethods.ByName("ListDevices")),
		connect.WithHandlerOptions(opts...),
	)
	devicesDeleteDeviceHandler := connect.NewUnaryHandler(
		DevicesDeleteDeviceProcedure,
		svc.DeleteDevice,
		connect.WithSchema(devicesMethods.ByName("DeleteDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesRenameDeviceHandler := connect.NewUnaryHandler(
		DevicesRenameDeviceProcedure,
		svc.RenameDevice,
		connect.WithSchema(devicesMethods.ByName("RenameDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesRotateDeviceKeyHandler := connect.NewUnaryHandler(
		DevicesRotateDeviceKeyProcedure,
		svc.RotateDeviceKey,
		connect.WithSchema(devicesMethods.ByName("RotateDeviceKey")),
		connect.WithHandlerOptions(opts...),
	)
	devicesListAllDevicesHandler := connect.NewUnaryHandler(
		DevicesListAllDevicesProcedure,
		svc.ListAllDevices,
		connect.WithSchema(devicesMethods.ByName("ListAllDevices")),
		connect.WithHandlerOptions(opts...),
	)
	devicesSetDeviceAccessHandler := connect.NewUnaryHandler(
		DevicesSetDeviceAccessProcedure,
		svc.SetDeviceAccess,
		connect.WithSchema(devicesMethods.ByName("SetDeviceAccess")),
		connect.WithHandlerOptions(opts...),
	)
	devicesSetDeviceRoutesHandler := connect.NewUnaryHandler(
		DevicesSetDeviceRoutesProcedure,
		svc.SetDeviceRoutes,
		connect.WithSchema(devicesMethods.ByName("SetDeviceRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.Devices/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DevicesAddDeviceProcedure:
			devicesAddDeviceHandler.ServeHTTP(w, r)
		case DevicesListDevicesProcedure:
			devicesListDevicesHandler.ServeHTTP(w, r)
		case DevicesDeleteDeviceProcedure:
			devicesDeleteDeviceHandler.ServeHTTP(w, r)
		case DevicesRenameDeviceProcedure:
			devicesRenameDeviceHandler.ServeHTTP(w, r)
		case DevicesRotateDeviceKeyProcedure:
			devicesRotateDeviceKeyHandler.ServeHTTP(w, r)
		case DevicesListAllDevicesProcedure:
			devicesListAllDevicesHandler.ServeHTTP(w, r)
		case DevicesSetDeviceAccessProcedure:
			devicesSetDeviceAccessHandler.ServeHTTP(w, r)
		case DevicesSetDeviceRoutesProcedure:
			devicesSetDeviceRoutesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDevicesHandler returns CodeUnimplemented from all methods.
type UnimplementedDevicesHandler struct{}

func (UnimplementedDevicesHandler) AddDevice(context.Context, *connect.Request[proto.AddDeviceReq]) (*connect.Response[proto.Device], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.AddDevice is not implemented"))
}

func (UnimplementedDevicesHandler) ListDevices(context.Context, *connect.Request[proto.ListDevicesReq]) (*connect.Response[proto.ListDevicesRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.ListDevices is not implemented"))
}

func (UnimplementedDevicesHandler) DeleteDevice(context.Context, *connect.Request[proto.DeleteDeviceReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.DeleteDevice is not implemented"))
}

func (UnimplementedDevicesHandler) RenameDevice(context.Context, *connect.Request[proto.RenameDeviceReq]) (*connect.Response[proto.Device], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.RenameDevice is not implemented"))
}

func (UnimplementedDevicesHandler) RotateDeviceKey(context.Context, *connect.Request[proto.RotateDeviceKeyReq]) (*connect.Response[proto.Device], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.RotateDeviceKey is not implemented"))
}

func (UnimplementedDevicesHandler) ListAllDevices(context.Context, *connect.Request[proto.ListAllDevicesReq]) (*connect.Response[proto.ListAllDevicesRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.ListAllDevices is not implemented"))
}

func (UnimplementedDevicesHandler) SetDeviceAccess(context.Context, *connect.Request[proto.SetDeviceAccessReq]) (*connect.Response[proto.Device], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.SetDeviceAccess is not implemented"))
}

func (UnimplementedDevicesHandler) SetDeviceRoutes(context.Context, *connect.Request[proto.SetDeviceRoutesReq]) (*connect.Response[proto.Device], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Devices.SetDeviceRoutes is not implemented"))
}
