// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/freifunkMUC/wg-access-server/proto/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerName is the fully-qualified name of the Server service.
	ServerName = "proto.Server"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerInfoProcedure is the fully-qualified name of the Server's Info RPC.
	ServerInfoProcedure = "/proto.Server/Info"
)

// ServerClient is a client for the proto.Server service.
type ServerClient interface {
	Info(context.Context, *connect.Request[proto.InfoReq]) (*connect.Response[proto.InfoRes], error)
}

// NewServerClient constructs a client for the proto.Server service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverMethods := proto.File_server_proto.Services().ByName("Server").Methods()
	return &serverClient{
		info: connect.NewClient[proto.InfoReq, proto.InfoRes](
			httpClient,
			baseURL+ServerInfoProcedure,
			connect.WithSchema(serverMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverClient implements ServerClient.
type serverClient struct {
	info *connect.Client[proto.InfoReq, proto.InfoRes]
}

// Info calls proto.Server.Info.
func (c *serverClient) Info(ctx context.Context, req *connect.Request[proto.InfoReq]) (*connect.Response[proto.InfoRes], error) {
	return c.info.CallUnary(ctx, req)
}

// ServerHandler is an implementation of the proto.Server service.
type ServerHandler interface {
	Info(context.Context, *connect.Request[proto.InfoReq]) (*connect.Response[proto.InfoRes], error)
}

// NewServerHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerHandler(svc ServerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverMethods := proto.File_server_proto.Services().ByName("Server").Methods()
	serverInfoHandler := connect.NewUnaryHandler(
		ServerInfoProcedure,
		svc.Info,
		connect.WithSchema(serverMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.Server/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerInfoProcedure:
			serverInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerHandler returns CodeUnimplemented from all methods.
type UnimplementedServerHandler struct{}

func (UnimplementedServerHandler) Info(context.Context, *connect.Request[proto.InfoReq]) (*connect.Response[proto.InfoRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Server.Info is not implemented"))
}
