// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sessions.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/freifunkMUC/wg-access-server/proto/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionsName is the fully-qualified name of the Sessions service.
	SessionsName = "proto.Sessions"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionsListSessionsProcedure is the fully-qualified name of the Sessions's ListSessions RPC.
	SessionsListSessionsProcedure = "/proto.Sessions/ListSessions"
	// SessionsDeleteSessionProcedure is the fully-qualified name of the Sessions's DeleteSession RPC.
	SessionsDeleteSessionProcedure = "/proto.Sessions/DeleteSession"
	// SessionsDeleteOtherSessionsProcedure is the fully-qualified name of the Sessions's
	// DeleteOtherSessions RPC.
	SessionsDeleteOtherSessionsProcedure = "/proto.Sessions/DeleteOtherSessions"
)

// SessionsClient is a client for the proto.Sessions service.
type SessionsClient interface {
	ListSessions(context.Context, *connect.Request[proto.ListSessionsReq]) (*connect.Response[proto.ListSessionsRes], error)
	DeleteSession(context.Context, *connect.Request[proto.DeleteSessionReq]) (*connect.Response[emptypb.Empty], error)
	// Ends every session but the one the request came with.
	DeleteOtherSessions(context.Context, *connect.Request[proto.DeleteOtherSessionsReq]) (*connect.Response[proto.DeleteOtherSessionsRes], error)
}

// NewSessionsClient constructs a client for the proto.Sessions service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionsMethods := proto.File_sessions_proto.Services().ByName("Sessions").Methods()
	return &sessionsClient{
		listSessions: connect.NewClient[proto.ListSessionsReq, proto.ListSessionsRes](
			httpClient,
			baseURL+SessionsListSessionsProcedure,
			connect.WithSchema(sessionsMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[proto.DeleteSessionReq, emptypb.Empty](
			httpClient,
			baseURL+SessionsDeleteSessionProcedure,
			connect.WithSchema(sessionsMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
		deleteOtherSessions: connect.NewClient[proto.DeleteOtherSessionsReq, proto.DeleteOtherSessionsRes](
			httpClient,
			baseURL+SessionsDeleteOtherSessionsProcedure,
			connect.WithSchema(sessionsMethods.ByName("DeleteOtherSessions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionsClient implements SessionsClient.
type sessionsClient struct {
	listSessions        *connect.Client[proto.ListSessionsReq, proto.ListSessionsRes]
	deleteSession       *connect.Client[proto.DeleteSessionReq, emptypb.Empty]
	deleteOtherSessions *connect.Client[proto.DeleteOtherSessionsReq, proto.DeleteOtherSessionsRes]
}

// ListSessions calls proto.Sessions.ListSessions.
func (c *sessionsClient) ListSessions(ctx context.Context, req *connect.Request[proto.ListSessionsReq]) (*connect.Response[proto.ListSessionsRes], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// DeleteSession calls proto.Sessions.DeleteSession.
func (c *sessionsClient) DeleteSession(ctx context.Context, req *connect.Request[proto.DeleteSessionReq]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// DeleteOtherSessions calls proto.Sessions.DeleteOtherSessions.
func (c *sessionsClient) DeleteOtherSessions(ctx context.Context, req *connect.Request[proto.DeleteOtherSessionsReq]) (*connect.Response[proto.DeleteOtherSessionsRes], error) {
	return c.deleteOtherSessions.CallUnary(ctx, req)
}

// SessionsHandler is an implementation of the proto.Sessions service.
type SessionsHandler interface {
	ListSessions(context.Context, *connect.Request[proto.ListSessionsReq]) (*connect.Response[proto.ListSessionsRes], error)
	DeleteSession(context.Context, *connect.Request[proto.DeleteSessionReq]) (*connect.Response[emptypb.Empty], error)
	// Ends every session but the one the request came with.
	DeleteOtherSessions(context.Context, *connect.Request[proto.DeleteOtherSessionsReq]) (*connect.Response[proto.DeleteOtherSessionsRes], error)
}

// NewSessionsHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionsHandler(svc SessionsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionsMethods := proto.File_sessions_proto.Services().ByName("Sessions").Methods()
	sessionsListSessionsHandler := connect.NewUnaryHandler(
		SessionsListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionsMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionsDeleteSessionHandler := connect.NewUnaryHandler(
		SessionsDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(sessionsMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionsDeleteOtherSessionsHandler := connect.NewUnaryHandler(
		SessionsDeleteOtherSessionsProcedure,
		svc.DeleteOtherSessions,
		connect.WithSchema(sessionsMethods.ByName("DeleteOtherSessions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.Sessions/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionsListSessionsProcedure:
			sessionsListSessionsHandler.ServeHTTP(w, r)
		case SessionsDeleteSessionProcedure:
			sessionsDeleteSessionHandler.ServeHTTP(w, r)
		case SessionsDeleteOtherSessionsProcedure:
			sessionsDeleteOtherSessionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionsHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionsHandler struct{}

func (UnimplementedSessionsHandler) ListSessions(context.Context, *connect.Request[proto.ListSessionsReq]) (*connect.Response[proto.ListSessionsRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Sessions.ListSessions is not implemented"))
}

func (UnimplementedSessionsHandler) DeleteSession(context.Context, *connect.Request[proto.DeleteSessionReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Sessions.DeleteSession is not implemented"))
}

func (UnimplementedSessionsHandler) DeleteOtherSessions(context.Context, *connect.Request[proto.DeleteOtherSessionsReq]) (*connect.Response[proto.DeleteOtherSessionsRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Sessions.DeleteOtherSessions is not implemented"))
}
