// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tokens.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/freifunkMUC/wg-access-server/proto/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TokensName is the fully-qualified name of the Tokens service.
	TokensName = "proto.Tokens"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokensCreateTokenProcedure is the fully-qualified name of the Tokens's CreateToken RPC.
	TokensCreateTokenProcedure = "/proto.Tokens/CreateToken"
	// TokensListTokensProcedure is the fully-qualified name of the Tokens's ListTokens RPC.
	TokensListTokensProcedure = "/proto.Tokens/ListTokens"
	// TokensDeleteTokenProcedure is the fully-qualified name of the Tokens's DeleteToken RPC.
	TokensDeleteTokenProcedure = "/proto.Tokens/DeleteToken"
	// TokensListAllTokensProcedure is the fully-qualified name of the Tokens's ListAllTokens RPC.
	TokensListAllTokensProcedure = "/proto.Tokens/ListAllTokens"
)

// TokensClient is a client for the proto.Tokens service.
type TokensClient interface {
	// Only with a browser session: a token cannot create further tokens.
	CreateToken(context.Context, *connect.Request[proto.CreateTokenReq]) (*connect.Response[proto.CreateTokenRes], error)
	ListTokens(context.Context, *connect.Request[proto.ListTokensReq]) (*connect.Response[proto.ListTokensRes], error)
	// Users can revoke their own tokens, admins any.
	DeleteToken(context.Context, *connect.Request[proto.DeleteTokenReq]) (*connect.Response[emptypb.Empty], error)
	// admin only
	ListAllTokens(context.Context, *connect.Request[proto.ListAllTokensReq]) (*connect.Response[proto.ListAllTokensRes], error)
}

// NewTokensClient constructs a client for the proto.Tokens service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTokensClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TokensClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tokensMethods := proto.File_tokens_proto.Services().ByName("Tokens").Methods()
	return &tokensClient{
		createToken: connect.NewClient[proto.CreateTokenReq, proto.CreateTokenRes](
			httpClient,
			baseURL+TokensCreateTokenProcedure,
			connect.WithSchema(tokensMethods.ByName("CreateToken")),
			connect.WithClientOptions(opts...),
		),
		listTokens: connect.NewClient[proto.ListTokensReq, proto.ListTokensRes](
			httpClient,
			baseURL+TokensListTokensProcedure,
			connect.WithSchema(tokensMethods.ByName("ListTokens")),
			connect.WithClientOptions(opts...),
		),
		deleteToken: connect.NewClient[proto.DeleteTokenReq, emptypb.Empty](
			httpClient,
			baseURL+TokensDeleteTokenProcedure,
			connect.WithSchema(tokensMethods.ByName("DeleteToken")),
			connect.WithClientOptions(opts...),
		),
		listAllTokens: connect.NewClient[proto.ListAllTokensReq, proto.ListAllTokensRes](
			httpClient,
			baseURL+TokensListAllTokensProcedure,
			connect.WithSchema(tokensMethods.ByName("ListAllTokens")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tokensClient implements TokensClient.
type tokensClient struct {
	createToken   *connect.Client[proto.CreateTokenReq, proto.CreateTokenRes]
	listTokens    *connect.Client[proto.ListTokensReq, proto.ListTokensRes]
	deleteToken   *connect.Client[proto.DeleteTokenReq, emptypb.Empty]
	listAllTokens *connect.Client[proto.ListAllTokensReq, proto.ListAllTokensRes]
}

// CreateToken calls proto.Tokens.CreateToken.
func (c *tokensClient) CreateToken(ctx context.Context, req *connect.Request[proto.CreateTokenReq]) (*connect.Response[proto.CreateTokenRes], error) {
	return c.createToken.CallUnary(ctx, req)
}

// ListTokens calls proto.Tokens.ListTokens.
func (c *tokensClient) ListTokens(ctx context.Context, req *connect.Request[proto.ListTokensReq]) (*connect.Response[proto.ListTokensRes], error) {
	return c.listTokens.CallUnary(ctx, req)
}

// DeleteToken calls proto.Tokens.DeleteToken.
func (c *tokensClient) DeleteToken(ctx context.Context, req *connect.Request[proto.DeleteTokenReq]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteToken.CallUnary(ctx, req)
}

// ListAllTokens calls proto.Tokens.ListAllTokens.
func (c *tokensClient) ListAllTokens(ctx context.Context, req *connect.Request[proto.ListAllTokensReq]) (*connect.Response[proto.ListAllTokensRes], error) {
	return c.listAllTokens.CallUnary(ctx, req)
}

// TokensHandler is an implementation of the proto.Tokens service.
type TokensHandler interface {
	// Only with a browser session: a token cannot create further tokens.
	CreateToken(context.Context, *connect.Request[proto.CreateTokenReq]) (*connect.Response[proto.CreateTokenRes], error)
	ListTokens(context.Context, *connect.Request[proto.ListTokensReq]) (*connect.Response[proto.ListTokensRes], error)
	// Users can revoke their own tokens, admins any.
	DeleteToken(context.Context, *connect.Request[proto.DeleteTokenReq]) (*connect.Response[emptypb.Empty], error)
	// admin only
	ListAllTokens(context.Context, *connect.Request[proto.ListAllTokensReq]) (*connect.Response[proto.ListAllTokensRes], error)
}

// NewTokensHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTokensHandler(svc TokensHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tokensMethods := proto.File_tokens_proto.Services().ByName("Tokens").Methods()
	tokensCreateTokenHandler := connect.NewUnaryHandler(
		TokensCreateTokenProcedure,
		svc.CreateToken,
		connect.WithSchema(tokensMethods.ByName("CreateToken")),
		connect.WithHandlerOptions(opts...),
	)
	tokensListTokensHandler := connect.NewUnaryHandler(
		TokensListTokensProcedure,
		svc.ListTokens,
		connect.WithSchema(tokensMethods.ByName("ListTokens")),
		connect.WithHandlerOptions(opts...),
	)
	tokensDeleteTokenHandler := connect.NewUnaryHandler(
		TokensDeleteTokenProcedure,
		svc.DeleteToken,
		connect.WithSchema(tokensMethods.ByName("DeleteToken")),
		connect.WithHandlerOptions(opts...),
	)
	tokensListAllTokensHandler := connect.NewUnaryHandler(
		TokensListAllTokensProcedure,
		svc.ListAllTokens,
		connect.WithSchema(tokensMethods.ByName("ListAllTokens")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.Tokens/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TokensCreateTokenProcedure:
			tokensCreateTokenHandler.ServeHTTP(w, r)
		case TokensListTokensProcedure:
			tokensListTokensHandler.ServeHTTP(w, r)
		case TokensDeleteTokenProcedure:
			tokensDeleteTokenHandler.ServeHTTP(w, r)
		case TokensListAllTokensProcedure:
			tokensListAllTokensHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTokensHandler returns CodeUnimplemented from all methods.
type UnimplementedTokensHandler struct{}

func (UnimplementedTokensHandler) CreateToken(context.Context, *connect.Request[proto.CreateTokenReq]) (*connect.Response[proto.CreateTokenRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Tokens.CreateToken is not implemented"))
}

func (UnimplementedTokensHandler) ListTokens(context.Context, *connect.Request[proto.ListTokensReq]) (*connect.Response[proto.ListTokensRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Tokens.ListTokens is not implemented"))
}

func (UnimplementedTokensHandler) DeleteToken(context.Context, *connect.Request[proto.DeleteTokenReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Tokens.DeleteToken is not implemented"))
}

func (UnimplementedTokensHandler) ListAllTokens(context.Context, *connect.Request[proto.ListAllTokensReq]) (*connect.Response[proto.ListAllTokensRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Tokens.ListAllTokens is not implemented"))
}
