// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: users.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/freifunkMUC/wg-access-server/proto/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UsersName is the fully-qualified name of the Users service.
	UsersName = "proto.Users"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UsersListUsersProcedure is the fully-qualified name of the Users's ListUsers RPC.
	UsersListUsersProcedure = "/proto.Users/ListUsers"
	// UsersDeleteUserProcedure is the fully-qualified name of the Users's DeleteUser RPC.
	UsersDeleteUserProcedure = "/proto.Users/DeleteUser"
	// UsersRevokeAccessProcedure is the fully-qualified name of the Users's RevokeAccess RPC.
	UsersRevokeAccessProcedure = "/proto.Users/RevokeAccess"
	// UsersChangePasswordProcedure is the fully-qualified name of the Users's ChangePassword RPC.
	UsersChangePasswordProcedure = "/proto.Users/ChangePassword"
	// UsersStartTwoFactorProcedure is the fully-qualified name of the Users's StartTwoFactor RPC.
	UsersStartTwoFactorProcedure = "/proto.Users/StartTwoFactor"
	// UsersConfirmTwoFactorProcedure is the fully-qualified name of the Users's ConfirmTwoFactor RPC.
	UsersConfirmTwoFactorProcedure = "/proto.Users/ConfirmTwoFactor"
	// UsersDisableTwoFactorProcedure is the fully-qualified name of the Users's DisableTwoFactor RPC.
	UsersDisableTwoFactorProcedure = "/proto.Users/DisableTwoFactor"
	// UsersNewRecoveryCodesProcedure is the fully-qualified name of the Users's NewRecoveryCodes RPC.
	UsersNewRecoveryCodesProcedure = "/proto.Users/NewRecoveryCodes"
	// UsersResetTwoFactorProcedure is the fully-qualified name of the Users's ResetTwoFactor RPC.
	UsersResetTwoFactorProcedure = "/proto.Users/ResetTwoFactor"
	// UsersListPasskeysProcedure is the fully-qualified name of the Users's ListPasskeys RPC.
	UsersListPasskeysProcedure = "/proto.Users/ListPasskeys"
	// UsersBeginPasskeyProcedure is the fully-qualified name of the Users's BeginPasskey RPC.
	UsersBeginPasskeyProcedure = "/proto.Users/BeginPasskey"
	// UsersFinishPasskeyProcedure is the fully-qualified name of the Users's FinishPasskey RPC.
	UsersFinishPasskeyProcedure = "/proto.Users/FinishPasskey"
	// UsersRenamePasskeyProcedure is the fully-qualified name of the Users's RenamePasskey RPC.
	UsersRenamePasskeyProcedure = "/proto.Users/RenamePasskey"
	// UsersDeletePasskeyProcedure is the fully-qualified name of the Users's DeletePasskey RPC.
	UsersDeletePasskeyProcedure = "/proto.Users/DeletePasskey"
)

// UsersClient is a client for the proto.Users service.
type UsersClient interface {
	// admin only
	ListUsers(context.Context, *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error)
	DeleteUser(context.Context, *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error)
	// Takes somebody's access away without deleting anything: their devices are
	// blocked, their API tokens revoked and their sessions ended.
	RevokeAccess(context.Context, *connect.Request[proto.RevokeAccessReq]) (*connect.Response[proto.RevokeAccessRes], error)
	// Changes your own password. Only for the built-in sign-in - with an
	// identity provider the password is theirs, not ours.
	ChangePassword(context.Context, *connect.Request[proto.ChangePasswordReq]) (*connect.Response[proto.ChangePasswordRes], error)
	// The second factor of the built-in sign-in: an authenticator app, and the
	// recovery codes for when the phone is gone. Your own only.
	StartTwoFactor(context.Context, *connect.Request[proto.StartTwoFactorReq]) (*connect.Response[proto.StartTwoFactorRes], error)
	ConfirmTwoFactor(context.Context, *connect.Request[proto.ConfirmTwoFactorReq]) (*connect.Response[proto.ConfirmTwoFactorRes], error)
	DisableTwoFactor(context.Context, *connect.Request[proto.DisableTwoFactorReq]) (*connect.Response[emptypb.Empty], error)
	// Replaces the recovery codes with a fresh set, for whoever has used most
	// of theirs or cannot find the paper any more.
	NewRecoveryCodes(context.Context, *connect.Request[proto.NewRecoveryCodesReq]) (*connect.Response[proto.NewRecoveryCodesRes], error)
	// admin only: take somebody's second factor away when their phone is gone
	ResetTwoFactor(context.Context, *connect.Request[proto.ResetTwoFactorReq]) (*connect.Response[emptypb.Empty], error)
	// Passkeys: the other second factor, a credential the browser holds and
	// that only this site can ask for. Your own only.
	ListPasskeys(context.Context, *connect.Request[proto.ListPasskeysReq]) (*connect.Response[proto.ListPasskeysRes], error)
	BeginPasskey(context.Context, *connect.Request[proto.BeginPasskeyReq]) (*connect.Response[proto.BeginPasskeyRes], error)
	FinishPasskey(context.Context, *connect.Request[proto.FinishPasskeyReq]) (*connect.Response[proto.Passkey], error)
	RenamePasskey(context.Context, *connect.Request[proto.RenamePasskeyReq]) (*connect.Response[proto.Passkey], error)
	DeletePasskey(context.Context, *connect.Request[proto.DeletePasskeyReq]) (*connect.Response[emptypb.Empty], error)
}

// NewUsersClient constructs a client for the proto.Users service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUsersClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UsersClient {
	baseURL = strings.TrimRight(baseURL, "/")
	usersMethods := proto.File_users_proto.Services().ByName("Users").Methods()
	return &usersClient{
		listUsers: connect.NewClient[proto.ListUsersReq, proto.ListUsersRes](
			httpClient,
			baseURL+UsersListUsersProcedure,
			connect.WithSchema(usersMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[proto.DeleteUserReq, emptypb.Empty](
			httpClient,
			baseURL+UsersDeleteUserProcedure,
			connect.WithSchema(usersMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		revokeAccess: connect.NewClient[proto.RevokeAccessReq, proto.RevokeAccessRes](
			httpClient,
			baseURL+UsersRevokeAccessProcedure,
			connect.WithSchema(usersMethods.ByName("RevokeAccess")),
			connect.WithClientOptions(opts...),
		),
		changePassword: connect.NewClient[proto.ChangePasswordReq, proto.ChangePasswordRes](
			httpClient,
			baseURL+UsersChangePasswordProcedure,
			connect.WithSchema(usersMethods.ByName("ChangePassword")),
			connect.WithClientOptions(opts...),
		),
		startTwoFactor: connect.NewClient[proto.StartTwoFactorReq, proto.StartTwoFactorRes](
			httpClient,
			baseURL+UsersStartTwoFactorProcedure,
			connect.WithSchema(usersMethods.ByName("StartTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		confirmTwoFactor: connect.NewClient[proto.ConfirmTwoFactorReq, proto.ConfirmTwoFactorRes](
			httpClient,
			baseURL+UsersConfirmTwoFactorProcedure,
			connect.WithSchema(usersMethods.ByName("ConfirmTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		disableTwoFactor: connect.NewClient[proto.DisableTwoFactorReq, emptypb.Empty](
			httpClient,
			baseURL+UsersDisableTwoFactorProcedure,
			connect.WithSchema(usersMethods.ByName("DisableTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		newRecoveryCodes: connect.NewClient[proto.NewRecoveryCodesReq, proto.NewRecoveryCodesRes](
			httpClient,
			baseURL+UsersNewRecoveryCodesProcedure,
			connect.WithSchema(usersMethods.ByName("NewRecoveryCodes")),
			connect.WithClientOptions(opts...),
		),
		resetTwoFactor: connect.NewClient[proto.ResetTwoFactorReq, emptypb.Empty](
			httpClient,
			baseURL+UsersResetTwoFactorProcedure,
			connect.WithSchema(usersMethods.ByName("ResetTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		listPasskeys: connect.NewClient[proto.ListPasskeysReq, proto.ListPasskeysRes](
			httpClient,
			baseURL+UsersListPasskeysProcedure,
			connect.WithSchema(usersMethods.ByName("ListPasskeys")),
			connect.WithClientOptions(opts...),
		),
		beginPasskey: connect.NewClient[proto.BeginPasskeyReq, proto.BeginPasskeyRes](
			httpClient,
			baseURL+UsersBeginPasskeyProcedure,
			connect.WithSchema(usersMethods.ByName("BeginPasskey")),
			connect.WithClientOptions(opts...),
		),
		finishPasskey: connect.NewClient[proto.FinishPasskeyReq, proto.Passkey](
			httpClient,
			baseURL+UsersFinishPasskeyProcedure,
			connect.WithSchema(usersMethods.ByName("FinishPasskey")),
			connect.WithClientOptions(opts...),
		),
		renamePasskey: connect.NewClient[proto.RenamePasskeyReq, proto.Passkey](
			httpClient,
			baseURL+UsersRenamePasskeyProcedure,
			connect.WithSchema(usersMethods.ByName("RenamePasskey")),
			connect.WithClientOptions(opts...),
		),
		deletePasskey: connect.NewClient[proto.DeletePasskeyReq, emptypb.Empty](
			httpClient,
			baseURL+UsersDeletePasskeyProcedure,
			connect.WithSchema(usersMethods.ByName("DeletePasskey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// usersClient implements UsersClient.
type usersClient struct {
	listUsers        *connect.Client[proto.ListUsersReq, proto.ListUsersRes]
	deleteUser       *connect.Client[proto.DeleteUserReq, emptypb.Empty]
	revokeAccess     *connect.Client[proto.RevokeAccessReq, proto.RevokeAccessRes]
	changePassword   *connect.Client[proto.ChangePasswordReq, proto.ChangePasswordRes]
	startTwoFactor   *connect.Client[proto.StartTwoFactorReq, proto.StartTwoFactorRes]
	confirmTwoFactor *connect.Client[proto.ConfirmTwoFactorReq, proto.ConfirmTwoFactorRes]
	disableTwoFactor *connect.Client[proto.DisableTwoFactorReq, emptypb.Empty]
	newRecoveryCodes *connect.Client[proto.NewRecoveryCodesReq, proto.NewRecoveryCodesRes]
	resetTwoFactor   *connect.Client[proto.ResetTwoFactorReq, emptypb.Empty]
	listPasskeys     *connect.Client[proto.ListPasskeysReq, proto.ListPasskeysRes]
	beginPasskey     *connect.Client[proto.BeginPasskeyReq, proto.BeginPasskeyRes]
	finishPasskey    *connect.Client[proto.FinishPasskeyReq, proto.Passkey]
	renamePasskey    *connect.Client[proto.RenamePasskeyReq, proto.Passkey]
	deletePasskey    *connect.Client[proto.DeletePasskeyReq, emptypb.Empty]
}

// ListUsers calls proto.Users.ListUsers.
func (c *usersClient) ListUsers(ctx context.Context, req *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// DeleteUser calls proto.Users.DeleteUser.
func (c *usersClient) DeleteUser(ctx context.Context, req *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// RevokeAccess calls proto.Users.RevokeAccess.
func (c *usersClient) RevokeAccess(ctx context.Context, req *connect.Request[proto.RevokeAccessReq]) (*connect.Response[proto.RevokeAccessRes], error) {
	return c.revokeAccess.CallUnary(ctx, req)
}

// ChangePassword calls proto.Users.ChangePassword.
func (c *usersClient) ChangePassword(ctx context.Context, req *connect.Request[proto.ChangePasswordReq]) (*connect.Response[proto.ChangePasswordRes], error) {
	return c.changePassword.CallUnary(ctx, req)
}

// StartTwoFactor calls proto.Users.StartTwoFactor.
func (c *usersClient) StartTwoFactor(ctx context.Context, req *connect.Request[proto.StartTwoFactorReq]) (*connect.Response[proto.StartTwoFactorRes], error) {
	return c.startTwoFactor.CallUnary(ctx, req)
}

// ConfirmTwoFactor calls proto.Users.ConfirmTwoFactor.
func (c *usersClient) ConfirmTwoFactor(ctx context.Context, req *connect.Request[proto.ConfirmTwoFactorReq]) (*connect.Response[proto.ConfirmTwoFactorRes], error) {
	return c.confirmTwoFactor.CallUnary(ctx, req)
}

// DisableTwoFactor calls proto.Users.DisableTwoFactor.
func (c *usersClient) DisableTwoFactor(ctx context.Context, req *connect.Request[proto.DisableTwoFactorReq]) (*connect.Response[emptypb.Empty], error) {
	return c.disableTwoFactor.CallUnary(ctx, req)
}

// NewRecoveryCodes calls proto.Users.NewRecoveryCodes.
func (c *usersClient) NewRecoveryCodes(ctx context.Context, req *connect.Request[proto.NewRecoveryCodesReq]) (*connect.Response[proto.NewRecoveryCodesRes], error) {
	return c.newRecoveryCodes.CallUnary(ctx, req)
}

// ResetTwoFactor calls proto.Users.ResetTwoFactor.
func (c *usersClient) ResetTwoFactor(ctx context.Context, req *connect.Request[proto.ResetTwoFactorReq]) (*connect.Response[emptypb.Empty], error) {
	return c.resetTwoFactor.CallUnary(ctx, req)
}

// ListPasskeys calls proto.Users.ListPasskeys.
func (c *usersClient) ListPasskeys(ctx context.Context, req *connect.Request[proto.ListPasskeysReq]) (*connect.Response[proto.ListPasskeysRes], error) {
	return c.listPasskeys.CallUnary(ctx, req)
}

// BeginPasskey calls proto.Users.BeginPasskey.
func (c *usersClient) BeginPasskey(ctx context.Context, req *connect.Request[proto.BeginPasskeyReq]) (*connect.Response[proto.BeginPasskeyRes], error) {
	return c.beginPasskey.CallUnary(ctx, req)
}

// FinishPasskey calls proto.Users.FinishPasskey.
func (c *usersClient) FinishPasskey(ctx context.Context, req *connect.Request[proto.FinishPasskeyReq]) (*connect.Response[proto.Passkey], error) {
	return c.finishPasskey.CallUnary(ctx, req)
}

// RenamePasskey calls proto.Users.RenamePasskey.
func (c *usersClient) RenamePasskey(ctx context.Context, req *connect.Request[proto.RenamePasskeyReq]) (*connect.Response[proto.Passkey], error) {
	return c.renamePasskey.CallUnary(ctx, req)
}

// DeletePasskey calls proto.Users.DeletePasskey.
func (c *usersClient) DeletePasskey(ctx context.Context, req *connect.Request[proto.DeletePasskeyReq]) (*connect.Response[emptypb.Empty], error) {
	return c.deletePasskey.CallUnary(ctx, req)
}

// UsersHandler is an implementation of the proto.Users service.
type UsersHandler interface {
	// admin only
	ListUsers(context.Context, *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error)
	DeleteUser(context.Context, *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error)
	// Takes somebody's access away without deleting anything: their devices are
	// blocked, their API tokens revoked and their sessions ended.
	RevokeAccess(context.Context, *connect.Request[proto.RevokeAccessReq]) (*connect.Response[proto.RevokeAccessRes], error)
	// Changes your own password. Only for the built-in sign-in - with an
	// identity provider the password is theirs, not ours.
	ChangePassword(context.Context, *connect.Request[proto.ChangePasswordReq]) (*connect.Response[proto.ChangePasswordRes], error)
	// The second factor of the built-in sign-in: an authenticator app, and the
	// recovery codes for when the phone is gone. Your own only.
	StartTwoFactor(context.Context, *connect.Request[proto.StartTwoFactorReq]) (*connect.Response[proto.StartTwoFactorRes], error)
	ConfirmTwoFactor(context.Context, *connect.Request[proto.ConfirmTwoFactorReq]) (*connect.Response[proto.ConfirmTwoFactorRes], error)
	DisableTwoFactor(context.Context, *connect.Request[proto.DisableTwoFactorReq]) (*connect.Response[emptypb.Empty], error)
	// Replaces the recovery codes with a fresh set, for whoever has used most
	// of theirs or cannot find the paper any more.
	NewRecoveryCodes(context.Context, *connect.Request[proto.NewRecoveryCodesReq]) (*connect.Response[proto.NewRecoveryCodesRes], error)
	// admin only: take somebody's second factor away when their phone is gone
	ResetTwoFactor(context.Context, *connect.Request[proto.ResetTwoFactorReq]) (*connect.Response[emptypb.Empty], error)
	// Passkeys: the other second factor, a credential the browser holds and
	// that only this site can ask for. Your own only.
	ListPasskeys(context.Context, *connect.Request[proto.ListPasskeysReq]) (*connect.Response[proto.ListPasskeysRes], error)
	BeginPasskey(context.Context, *connect.Request[proto.BeginPasskeyReq]) (*connect.Response[proto.BeginPasskeyRes], error)
	FinishPasskey(context.Context, *connect.Request[proto.FinishPasskeyReq]) (*connect.Response[proto.Passkey], error)
	RenamePasskey(context.Context, *connect.Request[proto.RenamePasskeyReq]) (*connect.Response[proto.Passkey], error)
	DeletePasskey(context.Context, *connect.Request[proto.DeletePasskeyReq]) (*connect.Response[emptypb.Empty], error)
}

// NewUsersHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUsersHandler(svc UsersHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	usersMethods := proto.File_users_proto.Services().ByName("Users").Methods()
	usersListUsersHandler := connect.NewUnaryHandler(
		UsersListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(usersMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	usersDeleteUserHandler := connect.NewUnaryHandler(
		UsersDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(usersMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	usersRevokeAccessHandler := connect.NewUnaryHandler(
		UsersRevokeAccessProcedure,
		svc.RevokeAccess,
		connect.WithSchema(usersMethods.ByName("RevokeAccess")),
		connect.WithHandlerOptions(opts...),
	)
	usersChangePasswordHandler := connect.NewUnaryHandler(
		UsersChangePasswordProcedure,
		svc.ChangePassword,
		connect.WithSchema(usersMethods.ByName("ChangePassword")),
		connect.WithHandlerOptions(opts...),
	)
	usersStartTwoFactorHandler := connect.NewUnaryHandler(
		UsersStartTwoFactorProcedure,
		svc.StartTwoFactor,
		connect.WithSchema(usersMethods.ByName("StartTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	usersConfirmTwoFactorHandler := connect.NewUnaryHandler(
		UsersConfirmTwoFactorProcedure,
		svc.ConfirmTwoFactor,
		connect.WithSchema(usersMethods.ByName("ConfirmTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	usersDisableTwoFactorHandler := connect.NewUnaryHandler(
		UsersDisableTwoFactorProcedure,
		svc.DisableTwoFactor,
		connect.WithSchema(usersMethods.ByName("DisableTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	usersNewRecoveryCodesHandler := connect.NewUnaryHandler(
		UsersNewRecoveryCodesProcedure,
		svc.NewRecoveryCodes,
		connect.WithSchema(usersMethods.ByName("NewRecoveryCodes")),
		connect.WithHandlerOptions(opts...),
	)
	usersResetTwoFactorHandler := connect.NewUnaryHandler(
		UsersResetTwoFactorProcedure,
		svc.ResetTwoFactor,
		connect.WithSchema(usersMethods.ByName("ResetTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	usersListPasskeysHandler := connect.NewUnaryHandler(
		UsersListPasskeysProcedure,
		svc.ListPasskeys,
		connect.WithSchema(usersMethods.ByName("ListPasskeys")),
		connect.WithHandlerOptions(opts...),
	)
	usersBeginPasskeyHandler := connect.NewUnaryHandler(
		UsersBeginPasskeyProcedure,
		svc.BeginPasskey,
		connect.WithSchema(usersMethods.ByName("BeginPasskey")),
		connect.WithHandlerOptions(opts...),
	)
	usersFinishPasskeyHandler := connect.NewUnaryHandler(
		UsersFinishPasskeyProcedure,
		svc.FinishPasskey,
		connect.WithSchema(usersMethods.ByName("FinishPasskey")),
		connect.WithHandlerOptions(opts...),
	)
	usersRenamePasskeyHandler := connect.NewUnaryHandler(
		UsersRenamePasskeyProcedure,
		svc.RenamePasskey,
		connect.WithSchema(usersMethods.ByName("RenamePasskey")),
		connect.WithHandlerOptions(opts...),
	)
	usersDeletePasskeyHandler := connect.NewUnaryHandler(
		UsersDeletePasskeyProcedure,
		svc.DeletePasskey,
		connect.WithSchema(usersMethods.ByName("DeletePasskey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.Users/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UsersListUsersProcedure:
			usersListUsersHandler.ServeHTTP(w, r)
		case UsersDeleteUserProcedure:
			usersDeleteUserHandler.ServeHTTP(w, r)
		case UsersRevokeAccessProcedure:
			usersRevokeAccessHandler.ServeHTTP(w, r)
		case UsersChangePasswordProcedure:
			usersChangePasswordHandler.ServeHTTP(w, r)
		case UsersStartTwoFactorProcedure:
			usersStartTwoFactorHandler.ServeHTTP(w, r)
		case UsersConfirmTwoFactorProcedure:
			usersConfirmTwoFactorHandler.ServeHTTP(w, r)
		case UsersDisableTwoFactorProcedure:
			usersDisableTwoFactorHandler.ServeHTTP(w, r)
		case UsersNewRecoveryCodesProcedure:
			usersNewRecoveryCodesHandler.ServeHTTP(w, r)
		case UsersResetTwoFactorProcedure:
			usersResetTwoFactorHandler.ServeHTTP(w, r)
		case UsersListPasskeysProcedure:
			usersListPasskeysHandler.ServeHTTP(w, r)
		case UsersBeginPasskeyProcedure:
			usersBeginPasskeyHandler.ServeHTTP(w, r)
		case UsersFinishPasskeyProcedure:
			usersFinishPasskeyHandler.ServeHTTP(w, r)
		case UsersRenamePasskeyProcedure:
			usersRenamePasskeyHandler.ServeHTTP(w, r)
		case UsersDeletePasskeyProcedure:
			usersDeletePasskeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUsersHandler returns CodeUnimplemented from all methods.
type UnimplementedUsersHandler struct{}

func (UnimplementedUsersHandler) ListUsers(context.Context, *connect.Request[proto.ListUsersReq]) (*connect.Response[proto.ListUsersRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.ListUsers is not implemented"))
}

func (UnimplementedUsersHandler) DeleteUser(context.Context, *connect.Request[proto.DeleteUserReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.DeleteUser is not implemented"))
}

func (UnimplementedUsersHandler) RevokeAccess(context.Context, *connect.Request[proto.RevokeAccessReq]) (*connect.Response[proto.RevokeAccessRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.RevokeAccess is not implemented"))
}

func (UnimplementedUsersHandler) ChangePassword(context.Context, *connect.Request[proto.ChangePasswordReq]) (*connect.Response[proto.ChangePasswordRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.ChangePassword is not implemented"))
}

func (UnimplementedUsersHandler) StartTwoFactor(context.Context, *connect.Request[proto.StartTwoFactorReq]) (*connect.Response[proto.StartTwoFactorRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.StartTwoFactor is not implemented"))
}

func (UnimplementedUsersHandler) ConfirmTwoFactor(context.Context, *connect.Request[proto.ConfirmTwoFactorReq]) (*connect.Response[proto.ConfirmTwoFactorRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.ConfirmTwoFactor is not implemented"))
}

func (UnimplementedUsersHandler) DisableTwoFactor(context.Context, *connect.Request[proto.DisableTwoFactorReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.DisableTwoFactor is not implemented"))
}

func (UnimplementedUsersHandler) NewRecoveryCodes(context.Context, *connect.Request[proto.NewRecoveryCodesReq]) (*connect.Response[proto.NewRecoveryCodesRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.NewRecoveryCodes is not implemented"))
}

func (UnimplementedUsersHandler) ResetTwoFactor(context.Context, *connect.Request[proto.ResetTwoFactorReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.ResetTwoFactor is not implemented"))
}

func (UnimplementedUsersHandler) ListPasskeys(context.Context, *connect.Request[proto.ListPasskeysReq]) (*connect.Response[proto.ListPasskeysRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.ListPasskeys is not implemented"))
}

func (UnimplementedUsersHandler) BeginPasskey(context.Context, *connect.Request[proto.BeginPasskeyReq]) (*connect.Response[proto.BeginPasskeyRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.BeginPasskey is not implemented"))
}

func (UnimplementedUsersHandler) FinishPasskey(context.Context, *connect.Request[proto.FinishPasskeyReq]) (*connect.Response[proto.Passkey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.FinishPasskey is not implemented"))
}

func (UnimplementedUsersHandler) RenamePasskey(context.Context, *connect.Request[proto.RenamePasskeyReq]) (*connect.Response[proto.Passkey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.RenamePasskey is not implemented"))
}

func (UnimplementedUsersHandler) DeletePasskey(context.Context, *connect.Request[proto.DeletePasskeyReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.Users.DeletePasskey is not implemented"))
}
