// Generated by protoc-gen-grpc-ts-web. DO NOT EDIT!
/* eslint-disable */
/* tslint:disable */

import * as jspb from 'google-protobuf';
import * as grpcWeb from 'grpc-web';

// grpc-web >= 2 types a MethodDescriptor's message classes as
// new (...args: unknown[]) => T, while the classes emitted by protoc-gen-js
// take an optional jspb.Message.MessageArray. The two are not assignable under
// strictFunctionTypes, so the constructors are bridged through this alias.
// It changes types only - the values handed to grpc-web are unchanged.
type MessageCtor<T> = new (...args: unknown[]) => T;

import * as googleProtobufWrappers from 'google-protobuf/google/protobuf/wrappers_pb';
import * as googleProtobufTimestamp from 'google-protobuf/google/protobuf/timestamp_pb';
import * as googleProtobufEmpty from 'google-protobuf/google/protobuf/empty_pb';

export class Devices {

	private client_ = new grpcWeb.GrpcWebClientBase({
		format: 'binary',
	});

	private methodInfoAddDevice = new grpcWeb.MethodDescriptor<AddDeviceReq, Device>(
		"AddDevice",
		'unary',
		AddDeviceReq as unknown as MessageCtor<AddDeviceReq>,
		Device as unknown as MessageCtor<Device>,
		(req: AddDeviceReq) => req.serializeBinary(),
		Device.deserializeBinary
	);

	private methodInfoListDevices = new grpcWeb.MethodDescriptor<ListDevicesReq, ListDevicesRes>(
		"ListDevices",
		'unary',
		ListDevicesReq as unknown as MessageCtor<ListDevicesReq>,
		ListDevicesRes as unknown as MessageCtor<ListDevicesRes>,
		(req: ListDevicesReq) => req.serializeBinary(),
		ListDevicesRes.deserializeBinary
	);

	private methodInfoDeleteDevice = new grpcWeb.MethodDescriptor<DeleteDeviceReq, googleProtobufEmpty.Empty>(
		"DeleteDevice",
		'unary',
		DeleteDeviceReq as unknown as MessageCtor<DeleteDeviceReq>,
		googleProtobufEmpty.Empty as unknown as MessageCtor<googleProtobufEmpty.Empty>,
		(req: DeleteDeviceReq) => req.serializeBinary(),
		googleProtobufEmpty.Empty.deserializeBinary
	);

	private methodInfoRenameDevice = new grpcWeb.MethodDescriptor<RenameDeviceReq, Device>(
		"RenameDevice",
		'unary',
		RenameDeviceReq as unknown as MessageCtor<RenameDeviceReq>,
		Device as unknown as MessageCtor<Device>,
		(req: RenameDeviceReq) => req.serializeBinary(),
		Device.deserializeBinary
	);

	private methodInfoRotateDeviceKey = new grpcWeb.MethodDescriptor<RotateDeviceKeyReq, Device>(
		"RotateDeviceKey",
		'unary',
		RotateDeviceKeyReq as unknown as MessageCtor<RotateDeviceKeyReq>,
		Device as unknown as MessageCtor<Device>,
		(req: RotateDeviceKeyReq) => req.serializeBinary(),
		Device.deserializeBinary
	);

	private methodInfoListAllDevices = new grpcWeb.MethodDescriptor<ListAllDevicesReq, ListAllDevicesRes>(
		"ListAllDevices",
		'unary',
		ListAllDevicesReq as unknown as MessageCtor<ListAllDevicesReq>,
		ListAllDevicesRes as unknown as MessageCtor<ListAllDevicesRes>,
		(req: ListAllDevicesReq) => req.serializeBinary(),
		ListAllDevicesRes.deserializeBinary
	);

	private methodInfoSetDeviceAccess = new grpcWeb.MethodDescriptor<SetDeviceAccessReq, Device>(
		"SetDeviceAccess",
		'unary',
		SetDeviceAccessReq as unknown as MessageCtor<SetDeviceAccessReq>,
		Device as unknown as MessageCtor<Device>,
		(req: SetDeviceAccessReq) => req.serializeBinary(),
		Device.deserializeBinary
	);

	private methodInfoSetDeviceRoutes = new grpcWeb.MethodDescriptor<SetDeviceRoutesReq, Device>(
		"SetDeviceRoutes",
		'unary',
		SetDeviceRoutesReq as unknown as MessageCtor<SetDeviceRoutesReq>,
		Device as unknown as MessageCtor<Device>,
		(req: SetDeviceRoutesReq) => req.serializeBinary(),
		Device.deserializeBinary
	);

	constructor(
		private hostname: string,
		private defaultMetadata?: () => grpcWeb.Metadata,
	) { }

	addDevice(req: AddDeviceReq.AsObject, metadata?: grpcWeb.Metadata): Promise<Device.AsObject> {
		return new Promise((resolve, reject) => {
			const message = AddDeviceReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/AddDevice',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoAddDevice,
				(err: grpcWeb.Error, res: Device) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	listDevices(req: ListDevicesReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ListDevicesRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ListDevicesReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/ListDevices',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoListDevices,
				(err: grpcWeb.Error, res: ListDevicesRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	deleteDevice(req: DeleteDeviceReq.AsObject, metadata?: grpcWeb.Metadata): Promise<googleProtobufEmpty.Empty.AsObject> {
		return new Promise((resolve, reject) => {
			const message = DeleteDeviceReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/DeleteDevice',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoDeleteDevice,
				(err: grpcWeb.Error, res: googleProtobufEmpty.Empty) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	renameDevice(req: RenameDeviceReq.AsObject, metadata?: grpcWeb.Metadata): Promise<Device.AsObject> {
		return new Promise((resolve, reject) => {
			const message = RenameDeviceReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/RenameDevice',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoRenameDevice,
				(err: grpcWeb.Error, res: Device) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	rotateDeviceKey(req: RotateDeviceKeyReq.AsObject, metadata?: grpcWeb.Metadata): Promise<Device.AsObject> {
		return new Promise((resolve, reject) => {
			const message = RotateDeviceKeyReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/RotateDeviceKey',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoRotateDeviceKey,
				(err: grpcWeb.Error, res: Device) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	listAllDevices(req: ListAllDevicesReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ListAllDevicesRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ListAllDevicesReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/ListAllDevices',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoListAllDevices,
				(err: grpcWeb.Error, res: ListAllDevicesRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	setDeviceAccess(req: SetDeviceAccessReq.AsObject, metadata?: grpcWeb.Metadata): Promise<Device.AsObject> {
		return new Promise((resolve, reject) => {
			const message = SetDeviceAccessReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/SetDeviceAccess',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoSetDeviceAccess,
				(err: grpcWeb.Error, res: Device) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	setDeviceRoutes(req: SetDeviceRoutesReq.AsObject, metadata?: grpcWeb.Metadata): Promise<Device.AsObject> {
		return new Promise((resolve, reject) => {
			const message = SetDeviceRoutesReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Devices/SetDeviceRoutes',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoSetDeviceRoutes,
				(err: grpcWeb.Error, res: Device) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

}




export declare namespace Device {
	export type AsObject = {
		name: string,
		owner: string,
		publicKey: string,
		address: string,
		createdAt?: googleProtobufTimestamp.Timestamp.AsObject,
		connected: boolean,
		lastHandshakeTime?: googleProtobufTimestamp.Timestamp.AsObject,
		receiveBytes: number,
		transmitBytes: number,
		endpoint: string,
		ownerName: string,
		ownerEmail: string,
		ownerProvider: string,
		presharedKey: string,
		disabled: boolean,
		expiresAt?: googleProtobufTimestamp.Timestamp.AsObject,
		routes: Array<string>,
	}
}

export class Device extends jspb.Message {

	private static repeatedFields_ = [
		17,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, Device.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getOwner(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setOwner(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 3, "");
	}

	setPublicKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 3, value);
	}

	getAddress(): string {return jspb.Message.getFieldWithDefault(this, 4, "");
	}

	setAddress(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 4, value);
	}

	getCreatedAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 5);
	}

	setCreatedAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 5, value);
	}

	getConnected(): boolean {return jspb.Message.getFieldWithDefault(this, 6, false);
	}

	setConnected(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 6, value);
	}

	getLastHandshakeTime(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 7);
	}

	setLastHandshakeTime(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 7, value);
	}

	getReceiveBytes(): number {return jspb.Message.getFieldWithDefault(this, 8, 0);
	}

	setReceiveBytes(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 8, value);
	}

	getTransmitBytes(): number {return jspb.Message.getFieldWithDefault(this, 9, 0);
	}

	setTransmitBytes(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 9, value);
	}

	getEndpoint(): string {return jspb.Message.getFieldWithDefault(this, 10, "");
	}

	setEndpoint(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 10, value);
	}

	getOwnerName(): string {return jspb.Message.getFieldWithDefault(this, 11, "");
	}

	setOwnerName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 11, value);
	}

	getOwnerEmail(): string {return jspb.Message.getFieldWithDefault(this, 12, "");
	}

	setOwnerEmail(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 12, value);
	}

	getOwnerProvider(): string {return jspb.Message.getFieldWithDefault(this, 13, "");
	}

	setOwnerProvider(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 13, value);
	}

	getPresharedKey(): string {return jspb.Message.getFieldWithDefault(this, 14, "");
	}

	setPresharedKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 14, value);
	}

	getDisabled(): boolean {return jspb.Message.getFieldWithDefault(this, 15, false);
	}

	setDisabled(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 15, value);
	}

	getExpiresAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 16);
	}

	setExpiresAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 16, value);
	}

	getRoutes(): Array<string> {return jspb.Message.getFieldWithDefault(this, 17, [""]);
	}

	setRoutes(value: Array<string>): void {
		(jspb.Message as any).setProto3StringField(this, 17, value);
	}

	addRoutes(value: string, index?: number): void {
		return jspb.Message.addToRepeatedField(this, 17, value, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		Device.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): Device.AsObject {
		let f: any;
		return {
			name: this.getName(),
			owner: this.getOwner(),
			publicKey: this.getPublicKey(),
			address: this.getAddress(),
			createdAt: (f = this.getCreatedAt()) && f.toObject(),
			connected: this.getConnected(),
			lastHandshakeTime: (f = this.getLastHandshakeTime()) && f.toObject(),
			receiveBytes: this.getReceiveBytes(),
			transmitBytes: this.getTransmitBytes(),
			endpoint: this.getEndpoint(),
			ownerName: this.getOwnerName(),
			ownerEmail: this.getOwnerEmail(),
			ownerProvider: this.getOwnerProvider(),
			presharedKey: this.getPresharedKey(),
			disabled: this.getDisabled(),
			expiresAt: (f = this.getExpiresAt()) && f.toObject(),
			routes: this.getRoutes(),
		};
	}

	static serializeBinaryToWriter(message: Device, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getOwner();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getPublicKey();
		if (field3.length > 0) {
			writer.writeString(3, field3);
		}
		const field4 = message.getAddress();
		if (field4.length > 0) {
			writer.writeString(4, field4);
		}
		const field5 = message.getCreatedAt();
		if (field5 != null) {
			writer.writeMessage(5, field5, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field6 = message.getConnected();
		if (field6 != false) {
			writer.writeBool(6, field6);
		}
		const field7 = message.getLastHandshakeTime();
		if (field7 != null) {
			writer.writeMessage(7, field7, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field8 = message.getReceiveBytes();
		if (field8 != 0) {
			writer.writeInt64(8, field8);
		}
		const field9 = message.getTransmitBytes();
		if (field9 != 0) {
			writer.writeInt64(9, field9);
		}
		const field10 = message.getEndpoint();
		if (field10.length > 0) {
			writer.writeString(10, field10);
		}
		const field11 = message.getOwnerName();
		if (field11.length > 0) {
			writer.writeString(11, field11);
		}
		const field12 = message.getOwnerEmail();
		if (field12.length > 0) {
			writer.writeString(12, field12);
		}
		const field13 = message.getOwnerProvider();
		if (field13.length > 0) {
			writer.writeString(13, field13);
		}
		const field14 = message.getPresharedKey();
		if (field14.length > 0) {
			writer.writeString(14, field14);
		}
		const field15 = message.getDisabled();
		if (field15 != false) {
			writer.writeBool(15, field15);
		}
		const field16 = message.getExpiresAt();
		if (field16 != null) {
			writer.writeMessage(16, field16, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field17 = message.getRoutes();
		if (field17.length > 0) {
			writer.writeRepeatedString(17, field17);
		}
	}

	static deserializeBinary(bytes: Uint8Array): Device {
		var reader = new jspb.BinaryReader(bytes);
		var message = new Device();
		return Device.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: Device, reader: jspb.BinaryReader): Device {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setOwner(field2);
				break;
			case 3:
				const field3 = reader.readString()
				message.setPublicKey(field3);
				break;
			case 4:
				const field4 = reader.readString()
				message.setAddress(field4);
				break;
			case 5:
				const field5 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field5, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setCreatedAt(field5);
				break;
			case 6:
				const field6 = reader.readBool()
				message.setConnected(field6);
				break;
			case 7:
				const field7 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field7, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setLastHandshakeTime(field7);
				break;
			case 8:
				const field8 = reader.readInt64()
				message.setReceiveBytes(field8);
				break;
			case 9:
				const field9 = reader.readInt64()
				message.setTransmitBytes(field9);
				break;
			case 10:
				const field10 = reader.readString()
				message.setEndpoint(field10);
				break;
			case 11:
				const field11 = reader.readString()
				message.setOwnerName(field11);
				break;
			case 12:
				const field12 = reader.readString()
				message.setOwnerEmail(field12);
				break;
			case 13:
				const field13 = reader.readString()
				message.setOwnerProvider(field13);
				break;
			case 14:
				const field14 = reader.readString()
				message.setPresharedKey(field14);
				break;
			case 15:
				const field15 = reader.readBool()
				message.setDisabled(field15);
				break;
			case 16:
				const field16 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field16, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setExpiresAt(field16);
				break;
			case 17:
				const field17 = reader.readString()
				message.addRoutes(field17);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace AddDeviceReq {
	export type AsObject = {
		name: string,
		publicKey: string,
		presharedKey: string,
		manualIpAssignment: boolean,
		manualIpv4Address: string,
		manualIpv6Address: string,
	}
}

export class AddDeviceReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, AddDeviceReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setPublicKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getPresharedKey(): string {return jspb.Message.getFieldWithDefault(this, 3, "");
	}

	setPresharedKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 3, value);
	}

	getManualIpAssignment(): boolean {return jspb.Message.getFieldWithDefault(this, 4, false);
	}

	setManualIpAssignment(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 4, value);
	}

	getManualIpv4Address(): string {return jspb.Message.getFieldWithDefault(this, 5, "");
	}

	setManualIpv4Address(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 5, value);
	}

	getManualIpv6Address(): string {return jspb.Message.getFieldWithDefault(this, 6, "");
	}

	setManualIpv6Address(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 6, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		AddDeviceReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): AddDeviceReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			publicKey: this.getPublicKey(),
			presharedKey: this.getPresharedKey(),
			manualIpAssignment: this.getManualIpAssignment(),
			manualIpv4Address: this.getManualIpv4Address(),
			manualIpv6Address: this.getManualIpv6Address(),
		};
	}

	static serializeBinaryToWriter(message: AddDeviceReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getPublicKey();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getPresharedKey();
		if (field3.length > 0) {
			writer.writeString(3, field3);
		}
		const field4 = message.getManualIpAssignment();
		if (field4 != false) {
			writer.writeBool(4, field4);
		}
		const field5 = message.getManualIpv4Address();
		if (field5.length > 0) {
			writer.writeString(5, field5);
		}
		const field6 = message.getManualIpv6Address();
		if (field6.length > 0) {
			writer.writeString(6, field6);
		}
	}

	static deserializeBinary(bytes: Uint8Array): AddDeviceReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new AddDeviceReq();
		return AddDeviceReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: AddDeviceReq, reader: jspb.BinaryReader): AddDeviceReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setPublicKey(field2);
				break;
			case 3:
				const field3 = reader.readString()
				message.setPresharedKey(field3);
				break;
			case 4:
				const field4 = reader.readBool()
				message.setManualIpAssignment(field4);
				break;
			case 5:
				const field5 = reader.readString()
				message.setManualIpv4Address(field5);
				break;
			case 6:
				const field6 = reader.readString()
				message.setManualIpv6Address(field6);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace RotateDeviceKeyReq {
	export type AsObject = {
		name: string,
		publicKey: string,
		presharedKey: string,
	}
}

export class RotateDeviceKeyReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, RotateDeviceKeyReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setPublicKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getPresharedKey(): string {return jspb.Message.getFieldWithDefault(this, 3, "");
	}

	setPresharedKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 3, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		RotateDeviceKeyReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): RotateDeviceKeyReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			publicKey: this.getPublicKey(),
			presharedKey: this.getPresharedKey(),
		};
	}

	static serializeBinaryToWriter(message: RotateDeviceKeyReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getPublicKey();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getPresharedKey();
		if (field3.length > 0) {
			writer.writeString(3, field3);
		}
	}

	static deserializeBinary(bytes: Uint8Array): RotateDeviceKeyReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new RotateDeviceKeyReq();
		return RotateDeviceKeyReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: RotateDeviceKeyReq, reader: jspb.BinaryReader): RotateDeviceKeyReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setPublicKey(field2);
				break;
			case 3:
				const field3 = reader.readString()
				message.setPresharedKey(field3);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace RenameDeviceReq {
	export type AsObject = {
		name: string,
		newName: string,
		owner?: googleProtobufWrappers.StringValue.AsObject,
	}
}

export class RenameDeviceReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, RenameDeviceReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getNewName(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setNewName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getOwner(): googleProtobufWrappers.StringValue {
		return jspb.Message.getWrapperField(this, googleProtobufWrappers.StringValue, 3);
	}

	setOwner(value?: googleProtobufWrappers.StringValue): void {
		(jspb.Message as any).setWrapperField(this, 3, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		RenameDeviceReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): RenameDeviceReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			newName: this.getNewName(),
			owner: (f = this.getOwner()) && f.toObject(),
		};
	}

	static serializeBinaryToWriter(message: RenameDeviceReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getNewName();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getOwner();
		if (field3 != null) {
			writer.writeMessage(3, field3, googleProtobufWrappers.StringValue.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): RenameDeviceReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new RenameDeviceReq();
		return RenameDeviceReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: RenameDeviceReq, reader: jspb.BinaryReader): RenameDeviceReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setNewName(field2);
				break;
			case 3:
				const field3 = new googleProtobufWrappers.StringValue();
				reader.readMessage(field3, googleProtobufWrappers.StringValue.deserializeBinaryFromReader);
				message.setOwner(field3);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListDevicesReq {
	export type AsObject = {
	}
}

export class ListDevicesReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListDevicesReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListDevicesReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListDevicesReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: ListDevicesReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): ListDevicesReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListDevicesReq();
		return ListDevicesReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListDevicesReq, reader: jspb.BinaryReader): ListDevicesReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListDevicesRes {
	export type AsObject = {
		items: Array<Device.AsObject>,
	}
}

export class ListDevicesRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListDevicesRes.repeatedFields_, null);
	}


	getItems(): Array<Device> {
		return jspb.Message.getRepeatedWrapperField(this, Device, 1);
	}

	setItems(value: Array<Device>): void {
		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
	}

	addItems(value?: Device, index?: number): Device {
		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Device, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListDevicesRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListDevicesRes.AsObject {
		let f: any;
		return {
			items: this.getItems().map((item) => item.toObject()),
		};
	}

	static serializeBinaryToWriter(message: ListDevicesRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getItems();
		if (field1.length > 0) {
			writer.writeRepeatedMessage(1, field1, Device.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ListDevicesRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListDevicesRes();
		return ListDevicesRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListDevicesRes, reader: jspb.BinaryReader): ListDevicesRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new Device();
				reader.readMessage(field1, Device.deserializeBinaryFromReader);
				message.addItems(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DeleteDeviceReq {
	export type AsObject = {
		name: string,
		owner?: googleProtobufWrappers.StringValue.AsObject,
	}
}

export class DeleteDeviceReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DeleteDeviceReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getOwner(): googleProtobufWrappers.StringValue {
		return jspb.Message.getWrapperField(this, googleProtobufWrappers.StringValue, 2);
	}

	setOwner(value?: googleProtobufWrappers.StringValue): void {
		(jspb.Message as any).setWrapperField(this, 2, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DeleteDeviceReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DeleteDeviceReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			owner: (f = this.getOwner()) && f.toObject(),
		};
	}

	static serializeBinaryToWriter(message: DeleteDeviceReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getOwner();
		if (field2 != null) {
			writer.writeMessage(2, field2, googleProtobufWrappers.StringValue.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): DeleteDeviceReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DeleteDeviceReq();
		return DeleteDeviceReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DeleteDeviceReq, reader: jspb.BinaryReader): DeleteDeviceReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = new googleProtobufWrappers.StringValue();
				reader.readMessage(field2, googleProtobufWrappers.StringValue.deserializeBinaryFromReader);
				message.setOwner(field2);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListAllDevicesReq {
	export type AsObject = {
	}
}

export class ListAllDevicesReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListAllDevicesReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListAllDevicesReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListAllDevicesReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: ListAllDevicesReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): ListAllDevicesReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListAllDevicesReq();
		return ListAllDevicesReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListAllDevicesReq, reader: jspb.BinaryReader): ListAllDevicesReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListAllDevicesRes {
	export type AsObject = {
		items: Array<Device.AsObject>,
	}
}

export class ListAllDevicesRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListAllDevicesRes.repeatedFields_, null);
	}


	getItems(): Array<Device> {
		return jspb.Message.getRepeatedWrapperField(this, Device, 1);
	}

	setItems(value: Array<Device>): void {
		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
	}

	addItems(value?: Device, index?: number): Device {
		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Device, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListAllDevicesRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListAllDevicesRes.AsObject {
		let f: any;
		return {
			items: this.getItems().map((item) => item.toObject()),
		};
	}

	static serializeBinaryToWriter(message: ListAllDevicesRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getItems();
		if (field1.length > 0) {
			writer.writeRepeatedMessage(1, field1, Device.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ListAllDevicesRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListAllDevicesRes();
		return ListAllDevicesRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListAllDevicesRes, reader: jspb.BinaryReader): ListAllDevicesRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new Device();
				reader.readMessage(field1, Device.deserializeBinaryFromReader);
				message.addItems(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace SetDeviceRoutesReq {
	export type AsObject = {
		name: string,
		owner?: googleProtobufWrappers.StringValue.AsObject,
		routes: Array<string>,
	}
}

export class SetDeviceRoutesReq extends jspb.Message {

	private static repeatedFields_ = [
		3,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, SetDeviceRoutesReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getOwner(): googleProtobufWrappers.StringValue {
		return jspb.Message.getWrapperField(this, googleProtobufWrappers.StringValue, 2);
	}

	setOwner(value?: googleProtobufWrappers.StringValue): void {
		(jspb.Message as any).setWrapperField(this, 2, value);
	}

	getRoutes(): Array<string> {return jspb.Message.getFieldWithDefault(this, 3, [""]);
	}

	setRoutes(value: Array<string>): void {
		(jspb.Message as any).setProto3StringField(this, 3, value);
	}

	addRoutes(value: string, index?: number): void {
		return jspb.Message.addToRepeatedField(this, 3, value, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		SetDeviceRoutesReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): SetDeviceRoutesReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			owner: (f = this.getOwner()) && f.toObject(),
			routes: this.getRoutes(),
		};
	}

	static serializeBinaryToWriter(message: SetDeviceRoutesReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getOwner();
		if (field2 != null) {
			writer.writeMessage(2, field2, googleProtobufWrappers.StringValue.serializeBinaryToWriter);
		}
		const field3 = message.getRoutes();
		if (field3.length > 0) {
			writer.writeRepeatedString(3, field3);
		}
	}

	static deserializeBinary(bytes: Uint8Array): SetDeviceRoutesReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new SetDeviceRoutesReq();
		return SetDeviceRoutesReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: SetDeviceRoutesReq, reader: jspb.BinaryReader): SetDeviceRoutesReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = new googleProtobufWrappers.StringValue();
				reader.readMessage(field2, googleProtobufWrappers.StringValue.deserializeBinaryFromReader);
				message.setOwner(field2);
				break;
			case 3:
				const field3 = reader.readString()
				message.addRoutes(field3);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace SetDeviceAccessReq {
	export type AsObject = {
		name: string,
		owner?: googleProtobufWrappers.StringValue.AsObject,
		disabled?: googleProtobufWrappers.BoolValue.AsObject,
		expiresAt?: googleProtobufTimestamp.Timestamp.AsObject,
		clearExpiresAt: boolean,
	}
}

export class SetDeviceAccessReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, SetDeviceAccessReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getOwner(): googleProtobufWrappers.StringValue {
		return jspb.Message.getWrapperField(this, googleProtobufWrappers.StringValue, 2);
	}

	setOwner(value?: googleProtobufWrappers.StringValue): void {
		(jspb.Message as any).setWrapperField(this, 2, value);
	}

	getDisabled(): googleProtobufWrappers.BoolValue {
		return jspb.Message.getWrapperField(this, googleProtobufWrappers.BoolValue, 3);
	}

	setDisabled(value?: googleProtobufWrappers.BoolValue): void {
		(jspb.Message as any).setWrapperField(this, 3, value);
	}

	getExpiresAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 4);
	}

	setExpiresAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 4, value);
	}

	getClearExpiresAt(): boolean {return jspb.Message.getFieldWithDefault(this, 5, false);
	}

	setClearExpiresAt(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 5, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		SetDeviceAccessReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): SetDeviceAccessReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			owner: (f = this.getOwner()) && f.toObject(),
			disabled: (f = this.getDisabled()) && f.toObject(),
			expiresAt: (f = this.getExpiresAt()) && f.toObject(),
			clearExpiresAt: this.getClearExpiresAt(),
		};
	}

	static serializeBinaryToWriter(message: SetDeviceAccessReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getOwner();
		if (field2 != null) {
			writer.writeMessage(2, field2, googleProtobufWrappers.StringValue.serializeBinaryToWriter);
		}
		const field3 = message.getDisabled();
		if (field3 != null) {
			writer.writeMessage(3, field3, googleProtobufWrappers.BoolValue.serializeBinaryToWriter);
		}
		const field4 = message.getExpiresAt();
		if (field4 != null) {
			writer.writeMessage(4, field4, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field5 = message.getClearExpiresAt();
		if (field5 != false) {
			writer.writeBool(5, field5);
		}
	}

	static deserializeBinary(bytes: Uint8Array): SetDeviceAccessReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new SetDeviceAccessReq();
		return SetDeviceAccessReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: SetDeviceAccessReq, reader: jspb.BinaryReader): SetDeviceAccessReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = new googleProtobufWrappers.StringValue();
				reader.readMessage(field2, googleProtobufWrappers.StringValue.deserializeBinaryFromReader);
				message.setOwner(field2);
				break;
			case 3:
				const field3 = new googleProtobufWrappers.BoolValue();
				reader.readMessage(field3, googleProtobufWrappers.BoolValue.deserializeBinaryFromReader);
				message.setDisabled(field3);
				break;
			case 4:
				const field4 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field4, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setExpiresAt(field4);
				break;
			case 5:
				const field5 = reader.readBool()
				message.setClearExpiresAt(field5);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}


function DeviceFromObject(obj: Device.AsObject | undefined): Device | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new Device();
	message.setName(obj.name);
	message.setOwner(obj.owner);
	message.setPublicKey(obj.publicKey);
	message.setAddress(obj.address);
	message.setCreatedAt(TimestampFromObject(obj.createdAt));
	message.setConnected(obj.connected);
	message.setLastHandshakeTime(TimestampFromObject(obj.lastHandshakeTime));
	message.setReceiveBytes(obj.receiveBytes);
	message.setTransmitBytes(obj.transmitBytes);
	message.setEndpoint(obj.endpoint);
	message.setOwnerName(obj.ownerName);
	message.setOwnerEmail(obj.ownerEmail);
	message.setOwnerProvider(obj.ownerProvider);
	message.setPresharedKey(obj.presharedKey);
	message.setDisabled(obj.disabled);
	message.setExpiresAt(TimestampFromObject(obj.expiresAt));
	(obj.routes || [])
		.forEach((item) => message.addRoutes(item));
	return message;
}

function TimestampFromObject(obj: googleProtobufTimestamp.Timestamp.AsObject | undefined): googleProtobufTimestamp.Timestamp | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufTimestamp.Timestamp();
	message.setSeconds(obj.seconds);
	message.setNanos(obj.nanos);
	return message;
}

function AddDeviceReqFromObject(obj: AddDeviceReq.AsObject | undefined): AddDeviceReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new AddDeviceReq();
	message.setName(obj.name);
	message.setPublicKey(obj.publicKey);
	message.setPresharedKey(obj.presharedKey);
	message.setManualIpAssignment(obj.manualIpAssignment);
	message.setManualIpv4Address(obj.manualIpv4Address);
	message.setManualIpv6Address(obj.manualIpv6Address);
	return message;
}

function RotateDeviceKeyReqFromObject(obj: RotateDeviceKeyReq.AsObject | undefined): RotateDeviceKeyReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new RotateDeviceKeyReq();
	message.setName(obj.name);
	message.setPublicKey(obj.publicKey);
	message.setPresharedKey(obj.presharedKey);
	return message;
}

function RenameDeviceReqFromObject(obj: RenameDeviceReq.AsObject | undefined): RenameDeviceReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new RenameDeviceReq();
	message.setName(obj.name);
	message.setNewName(obj.newName);
	message.setOwner(StringValueFromObject(obj.owner));
	return message;
}

function StringValueFromObject(obj: googleProtobufWrappers.StringValue.AsObject | undefined): googleProtobufWrappers.StringValue | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufWrappers.StringValue();
	message.setValue(obj.value);
	return message;
}

function ListDevicesReqFromObject(obj: ListDevicesReq.AsObject | undefined): ListDevicesReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListDevicesReq();
	return message;
}

function ListDevicesResFromObject(obj: ListDevicesRes.AsObject | undefined): ListDevicesRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListDevicesRes();
	(obj.items || [])
		.map((item) => DeviceFromObject(item))
		.forEach((item) => message.addItems(item));
	return message;
}

function DeleteDeviceReqFromObject(obj: DeleteDeviceReq.AsObject | undefined): DeleteDeviceReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DeleteDeviceReq();
	message.setName(obj.name);
	message.setOwner(StringValueFromObject(obj.owner));
	return message;
}

function ListAllDevicesReqFromObject(obj: ListAllDevicesReq.AsObject | undefined): ListAllDevicesReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListAllDevicesReq();
	return message;
}

function ListAllDevicesResFromObject(obj: ListAllDevicesRes.AsObject | undefined): ListAllDevicesRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListAllDevicesRes();
	(obj.items || [])
		.map((item) => DeviceFromObject(item))
		.forEach((item) => message.addItems(item));
	return message;
}

function SetDeviceRoutesReqFromObject(obj: SetDeviceRoutesReq.AsObject | undefined): SetDeviceRoutesReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new SetDeviceRoutesReq();
	message.setName(obj.name);
	message.setOwner(StringValueFromObject(obj.owner));
	(obj.routes || [])
		.forEach((item) => message.addRoutes(item));
	return message;
}

function SetDeviceAccessReqFromObject(obj: SetDeviceAccessReq.AsObject | undefined): SetDeviceAccessReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new SetDeviceAccessReq();
	message.setName(obj.name);
	message.setOwner(StringValueFromObject(obj.owner));
	message.setDisabled(BoolValueFromObject(obj.disabled));
	message.setExpiresAt(TimestampFromObject(obj.expiresAt));
	message.setClearExpiresAt(obj.clearExpiresAt);
	return message;
}

function BoolValueFromObject(obj: googleProtobufWrappers.BoolValue.AsObject | undefined): googleProtobufWrappers.BoolValue | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufWrappers.BoolValue();
	message.setValue(obj.value);
	return message;
}

function EmptyFromObject(obj: googleProtobufEmpty.Empty.AsObject | undefined): googleProtobufEmpty.Empty | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufEmpty.Empty();
	return message;
}

