// Generated by protoc-gen-grpc-ts-web. DO NOT EDIT!
/* eslint-disable */
/* tslint:disable */

import * as jspb from 'google-protobuf';
import * as grpcWeb from 'grpc-web';

import * as googleProtobufWrappers from 'google-protobuf/google/protobuf/wrappers_pb';
import * as googleProtobufDuration from 'google-protobuf/google/protobuf/duration_pb';
import * as buildinfo from './buildinfo_pb';

export class Server {

	private client_ = new grpcWeb.GrpcWebClientBase({
		format: 'text',
	});

	private methodInfoInfo = new grpcWeb.MethodDescriptor<InfoReq, InfoRes>(
		"Info",
		null,
		InfoReq,
		InfoRes,
		(req: InfoReq) => req.serializeBinary(),
		InfoRes.deserializeBinary
	);

	constructor(
		private hostname: string,
		private defaultMetadata?: () => grpcWeb.Metadata,
	) { }

	info(req: InfoReq.AsObject, metadata?: grpcWeb.Metadata): Promise<InfoRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = InfoReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Server/Info',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoInfo,
				(err: grpcWeb.Error, res: InfoRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

}




export declare namespace InfoReq {
	export type AsObject = {
	}
}

export class InfoReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, InfoReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		InfoReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): InfoReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: InfoReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): InfoReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new InfoReq();
		return InfoReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: InfoReq, reader: jspb.BinaryReader): InfoReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace InfoRes {
	export type AsObject = {
		publicKey: string,
		host?: googleProtobufWrappers.StringValue.AsObject,
		port: number,
		hostVpnIp: string,
		metadataEnabled: boolean,
		isAdmin: boolean,
		allowedIps: string,
		dnsEnabled: boolean,
		dnsAddress: string,
		filename: string,
		inactiveDeviceDeletionEnabled: boolean,
		inactiveDeviceGracePeriod?: googleProtobufDuration.Duration.AsObject,
		clientConfigDnsServers: string,
		clientConfigDnsSearchDomain: string,
		clientConfigMtu: number,
		buildInfo?: buildinfo.BuildInfo.AsObject,
		mtu: number,
		clientConfigPersistentKeepalive: number,
		amneziaJc: number,
		amneziaJmin: number,
		amneziaJmax: number,
		amneziaS1: number,
		amneziaS2: number,
		amneziaS3: number,
		amneziaS4: number,
		amneziaH1: string,
		amneziaH2: string,
		amneziaH3: string,
		amneziaH4: string,
		amneziaI1: string,
		amneziaI2: string,
		amneziaI3: string,
		amneziaI4: string,
		amneziaI5: string,
		amneziaContentPaddingAddition: string,
		amneziaRekeyAfterTime: string,
		amneziaRekeyTimeout: string,
		amneziaRejectAfterTime: string,
		amneziaKeepaliveTimeout: string,
		amneziaMaxHandshakeAttempts: string,
	}
}

export class InfoRes extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, InfoRes.repeatedFields_, null);
	}


	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setPublicKey(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getHost(): googleProtobufWrappers.StringValue {
		return jspb.Message.getWrapperField(this, googleProtobufWrappers.StringValue, 2);
	}

	setHost(value?: googleProtobufWrappers.StringValue): void {
		(jspb.Message as any).setWrapperField(this, 2, value);
	}

	getPort(): number {return jspb.Message.getFieldWithDefault(this, 3, 0);
	}

	setPort(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 3, value);
	}

	getHostVpnIp(): string {return jspb.Message.getFieldWithDefault(this, 4, "");
	}

	setHostVpnIp(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 4, value);
	}

	getMetadataEnabled(): boolean {return jspb.Message.getFieldWithDefault(this, 5, false);
	}

	setMetadataEnabled(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 5, value);
	}

	getIsAdmin(): boolean {return jspb.Message.getFieldWithDefault(this, 6, false);
	}

	setIsAdmin(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 6, value);
	}

	getAllowedIps(): string {return jspb.Message.getFieldWithDefault(this, 7, "");
	}

	setAllowedIps(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 7, value);
	}

	getDnsEnabled(): boolean {return jspb.Message.getFieldWithDefault(this, 8, false);
	}

	setDnsEnabled(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 8, value);
	}

	getDnsAddress(): string {return jspb.Message.getFieldWithDefault(this, 9, "");
	}

	setDnsAddress(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 9, value);
	}

	getFilename(): string {return jspb.Message.getFieldWithDefault(this, 10, "");
	}

	setFilename(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 10, value);
	}

	getInactiveDeviceDeletionEnabled(): boolean {return jspb.Message.getFieldWithDefault(this, 11, false);
	}

	setInactiveDeviceDeletionEnabled(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 11, value);
	}

	getInactiveDeviceGracePeriod(): googleProtobufDuration.Duration {
		return jspb.Message.getWrapperField(this, googleProtobufDuration.Duration, 12);
	}

	setInactiveDeviceGracePeriod(value?: googleProtobufDuration.Duration): void {
		(jspb.Message as any).setWrapperField(this, 12, value);
	}

	getClientConfigDnsServers(): string {return jspb.Message.getFieldWithDefault(this, 13, "");
	}

	setClientConfigDnsServers(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 13, value);
	}

	getClientConfigDnsSearchDomain(): string {return jspb.Message.getFieldWithDefault(this, 14, "");
	}

	setClientConfigDnsSearchDomain(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 14, value);
	}

	getClientConfigMtu(): number {return jspb.Message.getFieldWithDefault(this, 15, 0);
	}

	setClientConfigMtu(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 15, value);
	}

	getBuildInfo(): buildinfo.BuildInfo {
		return jspb.Message.getWrapperField(this, buildinfo.BuildInfo, 16);
	}

	setBuildInfo(value?: buildinfo.BuildInfo): void {
		(jspb.Message as any).setWrapperField(this, 16, value);
	}

	getMtu(): number {return jspb.Message.getFieldWithDefault(this, 17, 0);
	}

	setMtu(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 17, value);
	}

	getClientConfigPersistentKeepalive(): number {return jspb.Message.getFieldWithDefault(this, 18, 0);
	}

	setClientConfigPersistentKeepalive(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 18, value);
	}

	getAmneziaJc(): number {return jspb.Message.getFieldWithDefault(this, 19, 0);
	}

	setAmneziaJc(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 19, value);
	}

	getAmneziaJmin(): number {return jspb.Message.getFieldWithDefault(this, 20, 0);
	}

	setAmneziaJmin(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 20, value);
	}

	getAmneziaJmax(): number {return jspb.Message.getFieldWithDefault(this, 21, 0);
	}

	setAmneziaJmax(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 21, value);
	}

	getAmneziaS1(): number {return jspb.Message.getFieldWithDefault(this, 22, 0);
	}

	setAmneziaS1(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 22, value);
	}

	getAmneziaS2(): number {return jspb.Message.getFieldWithDefault(this, 23, 0);
	}

	setAmneziaS2(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 23, value);
	}

	getAmneziaS3(): number {return jspb.Message.getFieldWithDefault(this, 24, 0);
	}

	setAmneziaS3(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 24, value);
	}

	getAmneziaS4(): number {return jspb.Message.getFieldWithDefault(this, 25, 0);
	}

	setAmneziaS4(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 25, value);
	}

	getAmneziaH1(): string {return jspb.Message.getFieldWithDefault(this, 26, "");
	}

	setAmneziaH1(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 26, value);
	}

	getAmneziaH2(): string {return jspb.Message.getFieldWithDefault(this, 27, "");
	}

	setAmneziaH2(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 27, value);
	}

	getAmneziaH3(): string {return jspb.Message.getFieldWithDefault(this, 28, "");
	}

	setAmneziaH3(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 28, value);
	}

	getAmneziaH4(): string {return jspb.Message.getFieldWithDefault(this, 29, "");
	}

	setAmneziaH4(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 29, value);
	}

	getAmneziaI1(): string {return jspb.Message.getFieldWithDefault(this, 30, "");
	}

	setAmneziaI1(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 30, value);
	}

	getAmneziaI2(): string {return jspb.Message.getFieldWithDefault(this, 31, "");
	}

	setAmneziaI2(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 31, value);
	}

	getAmneziaI3(): string {return jspb.Message.getFieldWithDefault(this, 32, "");
	}

	setAmneziaI3(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 32, value);
	}

	getAmneziaI4(): string {return jspb.Message.getFieldWithDefault(this, 33, "");
	}

	setAmneziaI4(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 33, value);
	}

	getAmneziaI5(): string {return jspb.Message.getFieldWithDefault(this, 34, "");
	}

	setAmneziaI5(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 34, value);
	}

	getAmneziaContentPaddingAddition(): string {return jspb.Message.getFieldWithDefault(this, 35, "");
	}

	setAmneziaContentPaddingAddition(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 35, value);
	}

	getAmneziaRekeyAfterTime(): string {return jspb.Message.getFieldWithDefault(this, 36, "");
	}

	setAmneziaRekeyAfterTime(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 36, value);
	}

	getAmneziaRekeyTimeout(): string {return jspb.Message.getFieldWithDefault(this, 37, "");
	}

	setAmneziaRekeyTimeout(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 37, value);
	}

	getAmneziaRejectAfterTime(): string {return jspb.Message.getFieldWithDefault(this, 38, "");
	}

	setAmneziaRejectAfterTime(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 38, value);
	}

	getAmneziaKeepaliveTimeout(): string {return jspb.Message.getFieldWithDefault(this, 39, "");
	}

	setAmneziaKeepaliveTimeout(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 39, value);
	}

	getAmneziaMaxHandshakeAttempts(): string {return jspb.Message.getFieldWithDefault(this, 40, "");
	}

	setAmneziaMaxHandshakeAttempts(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 40, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		InfoRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): InfoRes.AsObject {
		let f: any;
		return {
			publicKey: this.getPublicKey(),
			host: (f = this.getHost()) && f.toObject(),
			port: this.getPort(),
			hostVpnIp: this.getHostVpnIp(),
			metadataEnabled: this.getMetadataEnabled(),
			isAdmin: this.getIsAdmin(),
			allowedIps: this.getAllowedIps(),
			dnsEnabled: this.getDnsEnabled(),
			dnsAddress: this.getDnsAddress(),
			filename: this.getFilename(),
			inactiveDeviceDeletionEnabled: this.getInactiveDeviceDeletionEnabled(),
			inactiveDeviceGracePeriod: (f = this.getInactiveDeviceGracePeriod()) && f.toObject(),
			clientConfigDnsServers: this.getClientConfigDnsServers(),
			clientConfigDnsSearchDomain: this.getClientConfigDnsSearchDomain(),
			clientConfigMtu: this.getClientConfigMtu(),
			buildInfo: (f = this.getBuildInfo()) && f.toObject(),
			mtu: this.getMtu(),
			clientConfigPersistentKeepalive: this.getClientConfigPersistentKeepalive(),
			amneziaJc: this.getAmneziaJc(),
			amneziaJmin: this.getAmneziaJmin(),
			amneziaJmax: this.getAmneziaJmax(),
			amneziaS1: this.getAmneziaS1(),
			amneziaS2: this.getAmneziaS2(),
			amneziaS3: this.getAmneziaS3(),
			amneziaS4: this.getAmneziaS4(),
			amneziaH1: this.getAmneziaH1(),
			amneziaH2: this.getAmneziaH2(),
			amneziaH3: this.getAmneziaH3(),
			amneziaH4: this.getAmneziaH4(),
			amneziaI1: this.getAmneziaI1(),
			amneziaI2: this.getAmneziaI2(),
			amneziaI3: this.getAmneziaI3(),
			amneziaI4: this.getAmneziaI4(),
			amneziaI5: this.getAmneziaI5(),
			amneziaContentPaddingAddition: this.getAmneziaContentPaddingAddition(),
			amneziaRekeyAfterTime: this.getAmneziaRekeyAfterTime(),
			amneziaRekeyTimeout: this.getAmneziaRekeyTimeout(),
			amneziaRejectAfterTime: this.getAmneziaRejectAfterTime(),
			amneziaKeepaliveTimeout: this.getAmneziaKeepaliveTimeout(),
			amneziaMaxHandshakeAttempts: this.getAmneziaMaxHandshakeAttempts(),
		};
	}

	static serializeBinaryToWriter(message: InfoRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getPublicKey();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getHost();
		if (field2 != null) {
			writer.writeMessage(2, field2, googleProtobufWrappers.StringValue.serializeBinaryToWriter);
		}
		const field3 = message.getPort();
		if (field3 != 0) {
			writer.writeInt32(3, field3);
		}
		const field4 = message.getHostVpnIp();
		if (field4.length > 0) {
			writer.writeString(4, field4);
		}
		const field5 = message.getMetadataEnabled();
		if (field5 != false) {
			writer.writeBool(5, field5);
		}
		const field6 = message.getIsAdmin();
		if (field6 != false) {
			writer.writeBool(6, field6);
		}
		const field7 = message.getAllowedIps();
		if (field7.length > 0) {
			writer.writeString(7, field7);
		}
		const field8 = message.getDnsEnabled();
		if (field8 != false) {
			writer.writeBool(8, field8);
		}
		const field9 = message.getDnsAddress();
		if (field9.length > 0) {
			writer.writeString(9, field9);
		}
		const field10 = message.getFilename();
		if (field10.length > 0) {
			writer.writeString(10, field10);
		}
		const field11 = message.getInactiveDeviceDeletionEnabled();
		if (field11 != false) {
			writer.writeBool(11, field11);
		}
		const field12 = message.getInactiveDeviceGracePeriod();
		if (field12 != null) {
			writer.writeMessage(12, field12, googleProtobufDuration.Duration.serializeBinaryToWriter);
		}
		const field13 = message.getClientConfigDnsServers();
		if (field13.length > 0) {
			writer.writeString(13, field13);
		}
		const field14 = message.getClientConfigDnsSearchDomain();
		if (field14.length > 0) {
			writer.writeString(14, field14);
		}
		const field15 = message.getClientConfigMtu();
		if (field15 != 0) {
			writer.writeInt32(15, field15);
		}
		const field16 = message.getBuildInfo();
		if (field16 != null) {
			writer.writeMessage(16, field16, buildinfo.BuildInfo.serializeBinaryToWriter);
		}
		const field17 = message.getMtu();
		if (field17 != 0) {
			writer.writeInt32(17, field17);
		}
		const field18 = message.getClientConfigPersistentKeepalive();
		if (field18 != 0) {
			writer.writeInt32(18, field18);
		}
		const field19 = message.getAmneziaJc();
		if (field19 != 0) {
			writer.writeUint32(19, field19);
		}
		const field20 = message.getAmneziaJmin();
		if (field20 != 0) {
			writer.writeUint32(20, field20);
		}
		const field21 = message.getAmneziaJmax();
		if (field21 != 0) {
			writer.writeUint32(21, field21);
		}
		const field22 = message.getAmneziaS1();
		if (field22 != 0) {
			writer.writeUint32(22, field22);
		}
		const field23 = message.getAmneziaS2();
		if (field23 != 0) {
			writer.writeUint32(23, field23);
		}
		const field24 = message.getAmneziaS3();
		if (field24 != 0) {
			writer.writeUint32(24, field24);
		}
		const field25 = message.getAmneziaS4();
		if (field25 != 0) {
			writer.writeUint32(25, field25);
		}
		const field26 = message.getAmneziaH1();
		if (field26.length > 0) {
			writer.writeString(26, field26);
		}
		const field27 = message.getAmneziaH2();
		if (field27.length > 0) {
			writer.writeString(27, field27);
		}
		const field28 = message.getAmneziaH3();
		if (field28.length > 0) {
			writer.writeString(28, field28);
		}
		const field29 = message.getAmneziaH4();
		if (field29.length > 0) {
			writer.writeString(29, field29);
		}
		const field30 = message.getAmneziaI1();
		if (field30.length > 0) {
			writer.writeString(30, field30);
		}
		const field31 = message.getAmneziaI2();
		if (field31.length > 0) {
			writer.writeString(31, field31);
		}
		const field32 = message.getAmneziaI3();
		if (field32.length > 0) {
			writer.writeString(32, field32);
		}
		const field33 = message.getAmneziaI4();
		if (field33.length > 0) {
			writer.writeString(33, field33);
		}
		const field34 = message.getAmneziaI5();
		if (field34.length > 0) {
			writer.writeString(34, field34);
		}
		const field35 = message.getAmneziaContentPaddingAddition();
		if (field35.length > 0) {
			writer.writeString(35, field35);
		}
		const field36 = message.getAmneziaRekeyAfterTime();
		if (field36.length > 0) {
			writer.writeString(36, field36);
		}
		const field37 = message.getAmneziaRekeyTimeout();
		if (field37.length > 0) {
			writer.writeString(37, field37);
		}
		const field38 = message.getAmneziaRejectAfterTime();
		if (field38.length > 0) {
			writer.writeString(38, field38);
		}
		const field39 = message.getAmneziaKeepaliveTimeout();
		if (field39.length > 0) {
			writer.writeString(39, field39);
		}
		const field40 = message.getAmneziaMaxHandshakeAttempts();
		if (field40.length > 0) {
			writer.writeString(40, field40);
		}
	}

	static deserializeBinary(bytes: Uint8Array): InfoRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new InfoRes();
		return InfoRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: InfoRes, reader: jspb.BinaryReader): InfoRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setPublicKey(field1);
				break;
			case 2:
				const field2 = new googleProtobufWrappers.StringValue();
				reader.readMessage(field2, googleProtobufWrappers.StringValue.deserializeBinaryFromReader);
				message.setHost(field2);
				break;
			case 3:
				const field3 = reader.readInt32()
				message.setPort(field3);
				break;
			case 4:
				const field4 = reader.readString()
				message.setHostVpnIp(field4);
				break;
			case 5:
				const field5 = reader.readBool()
				message.setMetadataEnabled(field5);
				break;
			case 6:
				const field6 = reader.readBool()
				message.setIsAdmin(field6);
				break;
			case 7:
				const field7 = reader.readString()
				message.setAllowedIps(field7);
				break;
			case 8:
				const field8 = reader.readBool()
				message.setDnsEnabled(field8);
				break;
			case 9:
				const field9 = reader.readString()
				message.setDnsAddress(field9);
				break;
			case 10:
				const field10 = reader.readString()
				message.setFilename(field10);
				break;
			case 11:
				const field11 = reader.readBool()
				message.setInactiveDeviceDeletionEnabled(field11);
				break;
			case 12:
				const field12 = new googleProtobufDuration.Duration();
				reader.readMessage(field12, googleProtobufDuration.Duration.deserializeBinaryFromReader);
				message.setInactiveDeviceGracePeriod(field12);
				break;
			case 13:
				const field13 = reader.readString()
				message.setClientConfigDnsServers(field13);
				break;
			case 14:
				const field14 = reader.readString()
				message.setClientConfigDnsSearchDomain(field14);
				break;
			case 15:
				const field15 = reader.readInt32()
				message.setClientConfigMtu(field15);
				break;
			case 16:
				const field16 = new buildinfo.BuildInfo();
				reader.readMessage(field16, buildinfo.BuildInfo.deserializeBinaryFromReader);
				message.setBuildInfo(field16);
				break;
			case 17:
				const field17 = reader.readInt32()
				message.setMtu(field17);
				break;
			case 18:
				const field18 = reader.readInt32()
				message.setClientConfigPersistentKeepalive(field18);
				break;
			case 19:
				const field19 = reader.readUint32()
				message.setAmneziaJc(field19);
				break;
			case 20:
				const field20 = reader.readUint32()
				message.setAmneziaJmin(field20);
				break;
			case 21:
				const field21 = reader.readUint32()
				message.setAmneziaJmax(field21);
				break;
			case 22:
				const field22 = reader.readUint32()
				message.setAmneziaS1(field22);
				break;
			case 23:
				const field23 = reader.readUint32()
				message.setAmneziaS2(field23);
				break;
			case 24:
				const field24 = reader.readUint32()
				message.setAmneziaS3(field24);
				break;
			case 25:
				const field25 = reader.readUint32()
				message.setAmneziaS4(field25);
				break;
			case 26:
				const field26 = reader.readString()
				message.setAmneziaH1(field26);
				break;
			case 27:
				const field27 = reader.readString()
				message.setAmneziaH2(field27);
				break;
			case 28:
				const field28 = reader.readString()
				message.setAmneziaH3(field28);
				break;
			case 29:
				const field29 = reader.readString()
				message.setAmneziaH4(field29);
				break;
			case 30:
				const field30 = reader.readString()
				message.setAmneziaI1(field30);
				break;
			case 31:
				const field31 = reader.readString()
				message.setAmneziaI2(field31);
				break;
			case 32:
				const field32 = reader.readString()
				message.setAmneziaI3(field32);
				break;
			case 33:
				const field33 = reader.readString()
				message.setAmneziaI4(field33);
				break;
			case 34:
				const field34 = reader.readString()
				message.setAmneziaI5(field34);
				break;
			case 35:
				const field35 = reader.readString()
				message.setAmneziaContentPaddingAddition(field35);
				break;
			case 36:
				const field36 = reader.readString()
				message.setAmneziaRekeyAfterTime(field36);
				break;
			case 37:
				const field37 = reader.readString()
				message.setAmneziaRekeyTimeout(field37);
				break;
			case 38:
				const field38 = reader.readString()
				message.setAmneziaRejectAfterTime(field38);
				break;
			case 39:
				const field39 = reader.readString()
				message.setAmneziaKeepaliveTimeout(field39);
				break;
			case 40:
				const field40 = reader.readString()
				message.setAmneziaMaxHandshakeAttempts(field40);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}


function InfoReqFromObject(obj: InfoReq.AsObject | undefined): InfoReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new InfoReq();
	return message;
}

function InfoResFromObject(obj: InfoRes.AsObject | undefined): InfoRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new InfoRes();
	message.setPublicKey(obj.publicKey);
	message.setHost(StringValueFromObject(obj.host));
	message.setPort(obj.port);
	message.setHostVpnIp(obj.hostVpnIp);
	message.setMetadataEnabled(obj.metadataEnabled);
	message.setIsAdmin(obj.isAdmin);
	message.setAllowedIps(obj.allowedIps);
	message.setDnsEnabled(obj.dnsEnabled);
	message.setDnsAddress(obj.dnsAddress);
	message.setFilename(obj.filename);
	message.setInactiveDeviceDeletionEnabled(obj.inactiveDeviceDeletionEnabled);
	message.setInactiveDeviceGracePeriod(DurationFromObject(obj.inactiveDeviceGracePeriod));
	message.setClientConfigDnsServers(obj.clientConfigDnsServers);
	message.setClientConfigDnsSearchDomain(obj.clientConfigDnsSearchDomain);
	message.setClientConfigMtu(obj.clientConfigMtu);
	message.setBuildInfo(BuildInfoFromObject(obj.buildInfo));
	message.setMtu(obj.mtu);
	message.setClientConfigPersistentKeepalive(obj.clientConfigPersistentKeepalive);
	message.setAmneziaJc(obj.amneziaJc);
	message.setAmneziaJmin(obj.amneziaJmin);
	message.setAmneziaJmax(obj.amneziaJmax);
	message.setAmneziaS1(obj.amneziaS1);
	message.setAmneziaS2(obj.amneziaS2);
	message.setAmneziaS3(obj.amneziaS3);
	message.setAmneziaS4(obj.amneziaS4);
	message.setAmneziaH1(obj.amneziaH1);
	message.setAmneziaH2(obj.amneziaH2);
	message.setAmneziaH3(obj.amneziaH3);
	message.setAmneziaH4(obj.amneziaH4);
	message.setAmneziaI1(obj.amneziaI1);
	message.setAmneziaI2(obj.amneziaI2);
	message.setAmneziaI3(obj.amneziaI3);
	message.setAmneziaI4(obj.amneziaI4);
	message.setAmneziaI5(obj.amneziaI5);
	message.setAmneziaContentPaddingAddition(obj.amneziaContentPaddingAddition);
	message.setAmneziaRekeyAfterTime(obj.amneziaRekeyAfterTime);
	message.setAmneziaRekeyTimeout(obj.amneziaRekeyTimeout);
	message.setAmneziaRejectAfterTime(obj.amneziaRejectAfterTime);
	message.setAmneziaKeepaliveTimeout(obj.amneziaKeepaliveTimeout);
	message.setAmneziaMaxHandshakeAttempts(obj.amneziaMaxHandshakeAttempts);
	return message;
}

function StringValueFromObject(obj: googleProtobufWrappers.StringValue.AsObject | undefined): googleProtobufWrappers.StringValue | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufWrappers.StringValue();
	message.setValue(obj.value);
	return message;
}

function DurationFromObject(obj: googleProtobufDuration.Duration.AsObject | undefined): googleProtobufDuration.Duration | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufDuration.Duration();
	message.setSeconds(obj.seconds);
	message.setNanos(obj.nanos);
	return message;
}

function BuildInfoFromObject(obj: buildinfo.BuildInfo.AsObject | undefined): buildinfo.BuildInfo | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new buildinfo.BuildInfo();
	message.setVersion(obj.version);
	message.setCommit(obj.commit);
	return message;
}

