// Generated by protoc-gen-grpc-ts-web. DO NOT EDIT!
/* eslint-disable */
/* tslint:disable */

import * as jspb from 'google-protobuf';
import * as grpcWeb from 'grpc-web';

// grpc-web >= 2 types a MethodDescriptor's message classes as
// new (...args: unknown[]) => T, while the classes emitted by protoc-gen-js
// take an optional jspb.Message.MessageArray. The two are not assignable under
// strictFunctionTypes, so the constructors are bridged through this alias.
// It changes types only - the values handed to grpc-web are unchanged.
type MessageCtor<T> = new (...args: unknown[]) => T;

import * as googleProtobufTimestamp from 'google-protobuf/google/protobuf/timestamp_pb';
import * as googleProtobufEmpty from 'google-protobuf/google/protobuf/empty_pb';

export class Sessions {

	private client_ = new grpcWeb.GrpcWebClientBase({
		format: 'binary',
	});

	private methodInfoListSessions = new grpcWeb.MethodDescriptor<ListSessionsReq, ListSessionsRes>(
		"ListSessions",
		'unary',
		ListSessionsReq as unknown as MessageCtor<ListSessionsReq>,
		ListSessionsRes as unknown as MessageCtor<ListSessionsRes>,
		(req: ListSessionsReq) => req.serializeBinary(),
		ListSessionsRes.deserializeBinary
	);

	private methodInfoDeleteSession = new grpcWeb.MethodDescriptor<DeleteSessionReq, googleProtobufEmpty.Empty>(
		"DeleteSession",
		'unary',
		DeleteSessionReq as unknown as MessageCtor<DeleteSessionReq>,
		googleProtobufEmpty.Empty as unknown as MessageCtor<googleProtobufEmpty.Empty>,
		(req: DeleteSessionReq) => req.serializeBinary(),
		googleProtobufEmpty.Empty.deserializeBinary
	);

	private methodInfoDeleteOtherSessions = new grpcWeb.MethodDescriptor<DeleteOtherSessionsReq, DeleteOtherSessionsRes>(
		"DeleteOtherSessions",
		'unary',
		DeleteOtherSessionsReq as unknown as MessageCtor<DeleteOtherSessionsReq>,
		DeleteOtherSessionsRes as unknown as MessageCtor<DeleteOtherSessionsRes>,
		(req: DeleteOtherSessionsReq) => req.serializeBinary(),
		DeleteOtherSessionsRes.deserializeBinary
	);

	constructor(
		private hostname: string,
		private defaultMetadata?: () => grpcWeb.Metadata,
	) { }

	listSessions(req: ListSessionsReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ListSessionsRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ListSessionsReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Sessions/ListSessions',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoListSessions,
				(err: grpcWeb.Error, res: ListSessionsRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	deleteSession(req: DeleteSessionReq.AsObject, metadata?: grpcWeb.Metadata): Promise<googleProtobufEmpty.Empty.AsObject> {
		return new Promise((resolve, reject) => {
			const message = DeleteSessionReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Sessions/DeleteSession',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoDeleteSession,
				(err: grpcWeb.Error, res: googleProtobufEmpty.Empty) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	deleteOtherSessions(req: DeleteOtherSessionsReq.AsObject, metadata?: grpcWeb.Metadata): Promise<DeleteOtherSessionsRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = DeleteOtherSessionsReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Sessions/DeleteOtherSessions',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoDeleteOtherSessions,
				(err: grpcWeb.Error, res: DeleteOtherSessionsRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

}




export declare namespace Session {
	export type AsObject = {
		id: string,
		userAgent: string,
		remoteAddr: string,
		createdAt?: googleProtobufTimestamp.Timestamp.AsObject,
		lastSeenAt?: googleProtobufTimestamp.Timestamp.AsObject,
		expiresAt?: googleProtobufTimestamp.Timestamp.AsObject,
		current: boolean,
	}
}

export class Session extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, Session.repeatedFields_, null);
	}


	getId(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setId(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getUserAgent(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setUserAgent(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getRemoteAddr(): string {return jspb.Message.getFieldWithDefault(this, 3, "");
	}

	setRemoteAddr(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 3, value);
	}

	getCreatedAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 4);
	}

	setCreatedAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 4, value);
	}

	getLastSeenAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 5);
	}

	setLastSeenAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 5, value);
	}

	getExpiresAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 6);
	}

	setExpiresAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 6, value);
	}

	getCurrent(): boolean {return jspb.Message.getFieldWithDefault(this, 7, false);
	}

	setCurrent(value: boolean): void {
		(jspb.Message as any).setProto3BooleanField(this, 7, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		Session.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): Session.AsObject {
		let f: any;
		return {
			id: this.getId(),
			userAgent: this.getUserAgent(),
			remoteAddr: this.getRemoteAddr(),
			createdAt: (f = this.getCreatedAt()) && f.toObject(),
			lastSeenAt: (f = this.getLastSeenAt()) && f.toObject(),
			expiresAt: (f = this.getExpiresAt()) && f.toObject(),
			current: this.getCurrent(),
		};
	}

	static serializeBinaryToWriter(message: Session, writer: jspb.BinaryWriter): void {
		const field1 = message.getId();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getUserAgent();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getRemoteAddr();
		if (field3.length > 0) {
			writer.writeString(3, field3);
		}
		const field4 = message.getCreatedAt();
		if (field4 != null) {
			writer.writeMessage(4, field4, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field5 = message.getLastSeenAt();
		if (field5 != null) {
			writer.writeMessage(5, field5, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field6 = message.getExpiresAt();
		if (field6 != null) {
			writer.writeMessage(6, field6, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field7 = message.getCurrent();
		if (field7 != false) {
			writer.writeBool(7, field7);
		}
	}

	static deserializeBinary(bytes: Uint8Array): Session {
		var reader = new jspb.BinaryReader(bytes);
		var message = new Session();
		return Session.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: Session, reader: jspb.BinaryReader): Session {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setId(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setUserAgent(field2);
				break;
			case 3:
				const field3 = reader.readString()
				message.setRemoteAddr(field3);
				break;
			case 4:
				const field4 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field4, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setCreatedAt(field4);
				break;
			case 5:
				const field5 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field5, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setLastSeenAt(field5);
				break;
			case 6:
				const field6 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field6, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setExpiresAt(field6);
				break;
			case 7:
				const field7 = reader.readBool()
				message.setCurrent(field7);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListSessionsReq {
	export type AsObject = {
	}
}

export class ListSessionsReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListSessionsReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListSessionsReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListSessionsReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: ListSessionsReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): ListSessionsReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListSessionsReq();
		return ListSessionsReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListSessionsReq, reader: jspb.BinaryReader): ListSessionsReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListSessionsRes {
	export type AsObject = {
		items: Array<Session.AsObject>,
	}
}

export class ListSessionsRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListSessionsRes.repeatedFields_, null);
	}


	getItems(): Array<Session> {
		return jspb.Message.getRepeatedWrapperField(this, Session, 1);
	}

	setItems(value: Array<Session>): void {
		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
	}

	addItems(value?: Session, index?: number): Session {
		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Session, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListSessionsRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListSessionsRes.AsObject {
		let f: any;
		return {
			items: this.getItems().map((item) => item.toObject()),
		};
	}

	static serializeBinaryToWriter(message: ListSessionsRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getItems();
		if (field1.length > 0) {
			writer.writeRepeatedMessage(1, field1, Session.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ListSessionsRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListSessionsRes();
		return ListSessionsRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListSessionsRes, reader: jspb.BinaryReader): ListSessionsRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new Session();
				reader.readMessage(field1, Session.deserializeBinaryFromReader);
				message.addItems(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DeleteSessionReq {
	export type AsObject = {
		id: string,
	}
}

export class DeleteSessionReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DeleteSessionReq.repeatedFields_, null);
	}


	getId(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setId(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DeleteSessionReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DeleteSessionReq.AsObject {
		let f: any;
		return {
			id: this.getId(),
		};
	}

	static serializeBinaryToWriter(message: DeleteSessionReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getId();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): DeleteSessionReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DeleteSessionReq();
		return DeleteSessionReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DeleteSessionReq, reader: jspb.BinaryReader): DeleteSessionReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setId(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DeleteOtherSessionsReq {
	export type AsObject = {
	}
}

export class DeleteOtherSessionsReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DeleteOtherSessionsReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DeleteOtherSessionsReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DeleteOtherSessionsReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: DeleteOtherSessionsReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): DeleteOtherSessionsReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DeleteOtherSessionsReq();
		return DeleteOtherSessionsReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DeleteOtherSessionsReq, reader: jspb.BinaryReader): DeleteOtherSessionsReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DeleteOtherSessionsRes {
	export type AsObject = {
		ended: number,
	}
}

export class DeleteOtherSessionsRes extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DeleteOtherSessionsRes.repeatedFields_, null);
	}


	getEnded(): number {return jspb.Message.getFieldWithDefault(this, 1, 0);
	}

	setEnded(value: number): void {
		(jspb.Message as any).setProto3IntField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DeleteOtherSessionsRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DeleteOtherSessionsRes.AsObject {
		let f: any;
		return {
			ended: this.getEnded(),
		};
	}

	static serializeBinaryToWriter(message: DeleteOtherSessionsRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getEnded();
		if (field1 != 0) {
			writer.writeInt32(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): DeleteOtherSessionsRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DeleteOtherSessionsRes();
		return DeleteOtherSessionsRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DeleteOtherSessionsRes, reader: jspb.BinaryReader): DeleteOtherSessionsRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readInt32()
				message.setEnded(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}


function SessionFromObject(obj: Session.AsObject | undefined): Session | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new Session();
	message.setId(obj.id);
	message.setUserAgent(obj.userAgent);
	message.setRemoteAddr(obj.remoteAddr);
	message.setCreatedAt(TimestampFromObject(obj.createdAt));
	message.setLastSeenAt(TimestampFromObject(obj.lastSeenAt));
	message.setExpiresAt(TimestampFromObject(obj.expiresAt));
	message.setCurrent(obj.current);
	return message;
}

function TimestampFromObject(obj: googleProtobufTimestamp.Timestamp.AsObject | undefined): googleProtobufTimestamp.Timestamp | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufTimestamp.Timestamp();
	message.setSeconds(obj.seconds);
	message.setNanos(obj.nanos);
	return message;
}

function ListSessionsReqFromObject(obj: ListSessionsReq.AsObject | undefined): ListSessionsReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListSessionsReq();
	return message;
}

function ListSessionsResFromObject(obj: ListSessionsRes.AsObject | undefined): ListSessionsRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListSessionsRes();
	(obj.items || [])
		.map((item) => SessionFromObject(item))
		.forEach((item) => message.addItems(item));
	return message;
}

function DeleteSessionReqFromObject(obj: DeleteSessionReq.AsObject | undefined): DeleteSessionReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DeleteSessionReq();
	message.setId(obj.id);
	return message;
}

function DeleteOtherSessionsReqFromObject(obj: DeleteOtherSessionsReq.AsObject | undefined): DeleteOtherSessionsReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DeleteOtherSessionsReq();
	return message;
}

function DeleteOtherSessionsResFromObject(obj: DeleteOtherSessionsRes.AsObject | undefined): DeleteOtherSessionsRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DeleteOtherSessionsRes();
	message.setEnded(obj.ended);
	return message;
}

function EmptyFromObject(obj: googleProtobufEmpty.Empty.AsObject | undefined): googleProtobufEmpty.Empty | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufEmpty.Empty();
	return message;
}

