// Generated by protoc-gen-grpc-ts-web. DO NOT EDIT!
/* eslint-disable */
/* tslint:disable */

import * as jspb from 'google-protobuf';
import * as grpcWeb from 'grpc-web';

// grpc-web >= 2 types a MethodDescriptor's message classes as
// new (...args: unknown[]) => T, while the classes emitted by protoc-gen-js
// take an optional jspb.Message.MessageArray. The two are not assignable under
// strictFunctionTypes, so the constructors are bridged through this alias.
// It changes types only - the values handed to grpc-web are unchanged.
type MessageCtor<T> = new (...args: unknown[]) => T;

import * as googleProtobufTimestamp from 'google-protobuf/google/protobuf/timestamp_pb';
import * as googleProtobufEmpty from 'google-protobuf/google/protobuf/empty_pb';

export class Tokens {

	private client_ = new grpcWeb.GrpcWebClientBase({
		format: 'binary',
	});

	private methodInfoCreateToken = new grpcWeb.MethodDescriptor<CreateTokenReq, CreateTokenRes>(
		"CreateToken",
		'unary',
		CreateTokenReq as unknown as MessageCtor<CreateTokenReq>,
		CreateTokenRes as unknown as MessageCtor<CreateTokenRes>,
		(req: CreateTokenReq) => req.serializeBinary(),
		CreateTokenRes.deserializeBinary
	);

	private methodInfoListTokens = new grpcWeb.MethodDescriptor<ListTokensReq, ListTokensRes>(
		"ListTokens",
		'unary',
		ListTokensReq as unknown as MessageCtor<ListTokensReq>,
		ListTokensRes as unknown as MessageCtor<ListTokensRes>,
		(req: ListTokensReq) => req.serializeBinary(),
		ListTokensRes.deserializeBinary
	);

	private methodInfoDeleteToken = new grpcWeb.MethodDescriptor<DeleteTokenReq, googleProtobufEmpty.Empty>(
		"DeleteToken",
		'unary',
		DeleteTokenReq as unknown as MessageCtor<DeleteTokenReq>,
		googleProtobufEmpty.Empty as unknown as MessageCtor<googleProtobufEmpty.Empty>,
		(req: DeleteTokenReq) => req.serializeBinary(),
		googleProtobufEmpty.Empty.deserializeBinary
	);

	private methodInfoListAllTokens = new grpcWeb.MethodDescriptor<ListAllTokensReq, ListAllTokensRes>(
		"ListAllTokens",
		'unary',
		ListAllTokensReq as unknown as MessageCtor<ListAllTokensReq>,
		ListAllTokensRes as unknown as MessageCtor<ListAllTokensRes>,
		(req: ListAllTokensReq) => req.serializeBinary(),
		ListAllTokensRes.deserializeBinary
	);

	constructor(
		private hostname: string,
		private defaultMetadata?: () => grpcWeb.Metadata,
	) { }

	createToken(req: CreateTokenReq.AsObject, metadata?: grpcWeb.Metadata): Promise<CreateTokenRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = CreateTokenReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Tokens/CreateToken',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoCreateToken,
				(err: grpcWeb.Error, res: CreateTokenRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	listTokens(req: ListTokensReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ListTokensRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ListTokensReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Tokens/ListTokens',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoListTokens,
				(err: grpcWeb.Error, res: ListTokensRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	deleteToken(req: DeleteTokenReq.AsObject, metadata?: grpcWeb.Metadata): Promise<googleProtobufEmpty.Empty.AsObject> {
		return new Promise((resolve, reject) => {
			const message = DeleteTokenReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Tokens/DeleteToken',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoDeleteToken,
				(err: grpcWeb.Error, res: googleProtobufEmpty.Empty) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

	listAllTokens(req: ListAllTokensReq.AsObject, metadata?: grpcWeb.Metadata): Promise<ListAllTokensRes.AsObject> {
		return new Promise((resolve, reject) => {
			const message = ListAllTokensReqFromObject(req);
			this.client_.rpcCall(
				this.hostname + '/proto.Tokens/ListAllTokens',
				message,
				Object.assign({}, this.defaultMetadata ? this.defaultMetadata() : {}, metadata),
				this.methodInfoListAllTokens,
				(err: grpcWeb.Error, res: ListAllTokensRes) => {
					if (err) {
						reject(err);
					} else {
						resolve(res.toObject());
					}
				},
			);
		});
	}

}




export declare namespace Token {
	export type AsObject = {
		id: string,
		name: string,
		owner: string,
		ownerName: string,
		createdAt?: googleProtobufTimestamp.Timestamp.AsObject,
		expiresAt?: googleProtobufTimestamp.Timestamp.AsObject,
		lastUsedAt?: googleProtobufTimestamp.Timestamp.AsObject,
	}
}

export class Token extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, Token.repeatedFields_, null);
	}


	getId(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setId(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getName(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	getOwner(): string {return jspb.Message.getFieldWithDefault(this, 3, "");
	}

	setOwner(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 3, value);
	}

	getOwnerName(): string {return jspb.Message.getFieldWithDefault(this, 4, "");
	}

	setOwnerName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 4, value);
	}

	getCreatedAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 5);
	}

	setCreatedAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 5, value);
	}

	getExpiresAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 6);
	}

	setExpiresAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 6, value);
	}

	getLastUsedAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 7);
	}

	setLastUsedAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 7, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		Token.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): Token.AsObject {
		let f: any;
		return {
			id: this.getId(),
			name: this.getName(),
			owner: this.getOwner(),
			ownerName: this.getOwnerName(),
			createdAt: (f = this.getCreatedAt()) && f.toObject(),
			expiresAt: (f = this.getExpiresAt()) && f.toObject(),
			lastUsedAt: (f = this.getLastUsedAt()) && f.toObject(),
		};
	}

	static serializeBinaryToWriter(message: Token, writer: jspb.BinaryWriter): void {
		const field1 = message.getId();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getName();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
		const field3 = message.getOwner();
		if (field3.length > 0) {
			writer.writeString(3, field3);
		}
		const field4 = message.getOwnerName();
		if (field4.length > 0) {
			writer.writeString(4, field4);
		}
		const field5 = message.getCreatedAt();
		if (field5 != null) {
			writer.writeMessage(5, field5, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field6 = message.getExpiresAt();
		if (field6 != null) {
			writer.writeMessage(6, field6, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
		const field7 = message.getLastUsedAt();
		if (field7 != null) {
			writer.writeMessage(7, field7, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): Token {
		var reader = new jspb.BinaryReader(bytes);
		var message = new Token();
		return Token.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: Token, reader: jspb.BinaryReader): Token {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setId(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setName(field2);
				break;
			case 3:
				const field3 = reader.readString()
				message.setOwner(field3);
				break;
			case 4:
				const field4 = reader.readString()
				message.setOwnerName(field4);
				break;
			case 5:
				const field5 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field5, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setCreatedAt(field5);
				break;
			case 6:
				const field6 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field6, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setExpiresAt(field6);
				break;
			case 7:
				const field7 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field7, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setLastUsedAt(field7);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace CreateTokenReq {
	export type AsObject = {
		name: string,
		expiresAt?: googleProtobufTimestamp.Timestamp.AsObject,
	}
}

export class CreateTokenReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, CreateTokenReq.repeatedFields_, null);
	}


	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setName(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	getExpiresAt(): googleProtobufTimestamp.Timestamp {
		return jspb.Message.getWrapperField(this, googleProtobufTimestamp.Timestamp, 2);
	}

	setExpiresAt(value?: googleProtobufTimestamp.Timestamp): void {
		(jspb.Message as any).setWrapperField(this, 2, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		CreateTokenReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): CreateTokenReq.AsObject {
		let f: any;
		return {
			name: this.getName(),
			expiresAt: (f = this.getExpiresAt()) && f.toObject(),
		};
	}

	static serializeBinaryToWriter(message: CreateTokenReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getName();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
		const field2 = message.getExpiresAt();
		if (field2 != null) {
			writer.writeMessage(2, field2, googleProtobufTimestamp.Timestamp.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): CreateTokenReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new CreateTokenReq();
		return CreateTokenReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: CreateTokenReq, reader: jspb.BinaryReader): CreateTokenReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setName(field1);
				break;
			case 2:
				const field2 = new googleProtobufTimestamp.Timestamp();
				reader.readMessage(field2, googleProtobufTimestamp.Timestamp.deserializeBinaryFromReader);
				message.setExpiresAt(field2);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace CreateTokenRes {
	export type AsObject = {
		token?: Token.AsObject,
		secret: string,
	}
}

export class CreateTokenRes extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, CreateTokenRes.repeatedFields_, null);
	}


	getToken(): Token {
		return jspb.Message.getWrapperField(this, Token, 1);
	}

	setToken(value?: Token): void {
		(jspb.Message as any).setWrapperField(this, 1, value);
	}

	getSecret(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
	}

	setSecret(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 2, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		CreateTokenRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): CreateTokenRes.AsObject {
		let f: any;
		return {
			token: (f = this.getToken()) && f.toObject(),
			secret: this.getSecret(),
		};
	}

	static serializeBinaryToWriter(message: CreateTokenRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getToken();
		if (field1 != null) {
			writer.writeMessage(1, field1, Token.serializeBinaryToWriter);
		}
		const field2 = message.getSecret();
		if (field2.length > 0) {
			writer.writeString(2, field2);
		}
	}

	static deserializeBinary(bytes: Uint8Array): CreateTokenRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new CreateTokenRes();
		return CreateTokenRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: CreateTokenRes, reader: jspb.BinaryReader): CreateTokenRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new Token();
				reader.readMessage(field1, Token.deserializeBinaryFromReader);
				message.setToken(field1);
				break;
			case 2:
				const field2 = reader.readString()
				message.setSecret(field2);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListTokensReq {
	export type AsObject = {
	}
}

export class ListTokensReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListTokensReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListTokensReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListTokensReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: ListTokensReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): ListTokensReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListTokensReq();
		return ListTokensReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListTokensReq, reader: jspb.BinaryReader): ListTokensReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListTokensRes {
	export type AsObject = {
		items: Array<Token.AsObject>,
	}
}

export class ListTokensRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListTokensRes.repeatedFields_, null);
	}


	getItems(): Array<Token> {
		return jspb.Message.getRepeatedWrapperField(this, Token, 1);
	}

	setItems(value: Array<Token>): void {
		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
	}

	addItems(value?: Token, index?: number): Token {
		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Token, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListTokensRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListTokensRes.AsObject {
		let f: any;
		return {
			items: this.getItems().map((item) => item.toObject()),
		};
	}

	static serializeBinaryToWriter(message: ListTokensRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getItems();
		if (field1.length > 0) {
			writer.writeRepeatedMessage(1, field1, Token.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ListTokensRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListTokensRes();
		return ListTokensRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListTokensRes, reader: jspb.BinaryReader): ListTokensRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new Token();
				reader.readMessage(field1, Token.deserializeBinaryFromReader);
				message.addItems(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace DeleteTokenReq {
	export type AsObject = {
		id: string,
	}
}

export class DeleteTokenReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, DeleteTokenReq.repeatedFields_, null);
	}


	getId(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
	}

	setId(value: string): void {
		(jspb.Message as any).setProto3StringField(this, 1, value);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		DeleteTokenReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): DeleteTokenReq.AsObject {
		let f: any;
		return {
			id: this.getId(),
		};
	}

	static serializeBinaryToWriter(message: DeleteTokenReq, writer: jspb.BinaryWriter): void {
		const field1 = message.getId();
		if (field1.length > 0) {
			writer.writeString(1, field1);
		}
	}

	static deserializeBinary(bytes: Uint8Array): DeleteTokenReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new DeleteTokenReq();
		return DeleteTokenReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: DeleteTokenReq, reader: jspb.BinaryReader): DeleteTokenReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = reader.readString()
				message.setId(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListAllTokensReq {
	export type AsObject = {
	}
}

export class ListAllTokensReq extends jspb.Message {

	private static repeatedFields_ = [
		
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListAllTokensReq.repeatedFields_, null);
	}


	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListAllTokensReq.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListAllTokensReq.AsObject {
		let f: any;
		return {
		};
	}

	static serializeBinaryToWriter(message: ListAllTokensReq, writer: jspb.BinaryWriter): void {
	}

	static deserializeBinary(bytes: Uint8Array): ListAllTokensReq {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListAllTokensReq();
		return ListAllTokensReq.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListAllTokensReq, reader: jspb.BinaryReader): ListAllTokensReq {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}
export declare namespace ListAllTokensRes {
	export type AsObject = {
		items: Array<Token.AsObject>,
	}
}

export class ListAllTokensRes extends jspb.Message {

	private static repeatedFields_ = [
		1,
	];

	constructor(data?: jspb.Message.MessageArray) {
		super();
		jspb.Message.initialize(this, data || [], 0, -1, ListAllTokensRes.repeatedFields_, null);
	}


	getItems(): Array<Token> {
		return jspb.Message.getRepeatedWrapperField(this, Token, 1);
	}

	setItems(value: Array<Token>): void {
		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
	}

	addItems(value?: Token, index?: number): Token {
		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Token, index);
	}

	serializeBinary(): Uint8Array {
		const writer = new jspb.BinaryWriter();
		ListAllTokensRes.serializeBinaryToWriter(this, writer);
		return writer.getResultBuffer();
	}

	toObject(): ListAllTokensRes.AsObject {
		let f: any;
		return {
			items: this.getItems().map((item) => item.toObject()),
		};
	}

	static serializeBinaryToWriter(message: ListAllTokensRes, writer: jspb.BinaryWriter): void {
		const field1 = message.getItems();
		if (field1.length > 0) {
			writer.writeRepeatedMessage(1, field1, Token.serializeBinaryToWriter);
		}
	}

	static deserializeBinary(bytes: Uint8Array): ListAllTokensRes {
		var reader = new jspb.BinaryReader(bytes);
		var message = new ListAllTokensRes();
		return ListAllTokensRes.deserializeBinaryFromReader(message, reader);
	}

	static deserializeBinaryFromReader(message: ListAllTokensRes, reader: jspb.BinaryReader): ListAllTokensRes {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			const field = reader.getFieldNumber();
			switch (field) {
			case 1:
				const field1 = new Token();
				reader.readMessage(field1, Token.deserializeBinaryFromReader);
				message.addItems(field1);
				break;
			default:
				reader.skipField();
				break;
			}
		}
		return message;
	}

}


function TokenFromObject(obj: Token.AsObject | undefined): Token | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new Token();
	message.setId(obj.id);
	message.setName(obj.name);
	message.setOwner(obj.owner);
	message.setOwnerName(obj.ownerName);
	message.setCreatedAt(TimestampFromObject(obj.createdAt));
	message.setExpiresAt(TimestampFromObject(obj.expiresAt));
	message.setLastUsedAt(TimestampFromObject(obj.lastUsedAt));
	return message;
}

function TimestampFromObject(obj: googleProtobufTimestamp.Timestamp.AsObject | undefined): googleProtobufTimestamp.Timestamp | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufTimestamp.Timestamp();
	message.setSeconds(obj.seconds);
	message.setNanos(obj.nanos);
	return message;
}

function CreateTokenReqFromObject(obj: CreateTokenReq.AsObject | undefined): CreateTokenReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new CreateTokenReq();
	message.setName(obj.name);
	message.setExpiresAt(TimestampFromObject(obj.expiresAt));
	return message;
}

function CreateTokenResFromObject(obj: CreateTokenRes.AsObject | undefined): CreateTokenRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new CreateTokenRes();
	message.setToken(TokenFromObject(obj.token));
	message.setSecret(obj.secret);
	return message;
}

function ListTokensReqFromObject(obj: ListTokensReq.AsObject | undefined): ListTokensReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListTokensReq();
	return message;
}

function ListTokensResFromObject(obj: ListTokensRes.AsObject | undefined): ListTokensRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListTokensRes();
	(obj.items || [])
		.map((item) => TokenFromObject(item))
		.forEach((item) => message.addItems(item));
	return message;
}

function DeleteTokenReqFromObject(obj: DeleteTokenReq.AsObject | undefined): DeleteTokenReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new DeleteTokenReq();
	message.setId(obj.id);
	return message;
}

function ListAllTokensReqFromObject(obj: ListAllTokensReq.AsObject | undefined): ListAllTokensReq | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListAllTokensReq();
	return message;
}

function ListAllTokensResFromObject(obj: ListAllTokensRes.AsObject | undefined): ListAllTokensRes | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new ListAllTokensRes();
	(obj.items || [])
		.map((item) => TokenFromObject(item))
		.forEach((item) => message.addItems(item));
	return message;
}

function EmptyFromObject(obj: googleProtobufEmpty.Empty.AsObject | undefined): googleProtobufEmpty.Empty | undefined {
	if (obj === undefined) {
		return undefined;
	}
	const message = new googleProtobufEmpty.Empty();
	return message;
}

