// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: buildinfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_buildinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_buildinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_buildinfo_proto_rawDescGZIP(), []int{0}
}

func (x *BuildInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildInfo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

var File_buildinfo_proto protoreflect.FileDescriptor

const file_buildinfo_proto_rawDesc = "" +
	"\n" +
	"\x0fbuildinfo.proto\x12\x05proto\"=\n" +
	"\tBuildInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commitB5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_buildinfo_proto_rawDescOnce sync.Once
	file_buildinfo_proto_rawDescData []byte
)

func file_buildinfo_proto_rawDescGZIP() []byte {
	file_buildinfo_proto_rawDescOnce.Do(func() {
		file_buildinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buildinfo_proto_rawDesc), len(file_buildinfo_proto_rawDesc)))
	})
	return file_buildinfo_proto_rawDescData
}

var file_buildinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_buildinfo_proto_goTypes = []any{
	(*BuildInfo)(nil), // 0: proto.BuildInfo
}
var file_buildinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buildinfo_proto_init() }
func file_buildinfo_proto_init() {
	if File_buildinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buildinfo_proto_rawDesc), len(file_buildinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buildinfo_proto_goTypes,
		DependencyIndexes: file_buildinfo_proto_depIdxs,
		MessageInfos:      file_buildinfo_proto_msgTypes,
	}.Build()
	File_buildinfo_proto = out.File
	file_buildinfo_proto_goTypes = nil
	file_buildinfo_proto_depIdxs = nil
}
