// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: devices.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner             string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	PublicKey         string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Connected         bool                   `protobuf:"varint,6,opt,name=connected,proto3" json:"connected,omitempty"`
	LastHandshakeTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_handshake_time,json=lastHandshakeTime,proto3" json:"last_handshake_time,omitempty"`
	ReceiveBytes      int64                  `protobuf:"varint,8,opt,name=receive_bytes,json=receiveBytes,proto3" json:"receive_bytes,omitempty"`
	TransmitBytes     int64                  `protobuf:"varint,9,opt,name=transmit_bytes,json=transmitBytes,proto3" json:"transmit_bytes,omitempty"`
	Endpoint          string                 `protobuf:"bytes,10,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	OwnerName         string                 `protobuf:"bytes,11,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerEmail        string                 `protobuf:"bytes,12,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	OwnerProvider     string                 `protobuf:"bytes,13,opt,name=owner_provider,json=ownerProvider,proto3" json:"owner_provider,omitempty"`
	PresharedKey      string                 `protobuf:"bytes,14,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	// disabled: an admin blocked the device, so it has no WireGuard peer and
	// cannot connect until the block is lifted.
	Disabled bool `protobuf:"varint,15,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// unset: the device's access does not expire. Once the time has passed the
	// device loses its peer, like a disabled one.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// the networks behind the device, in CIDR notation. They are part of the
	// peer's allowed IPs, so traffic for them goes through this device.
	Routes        []string `protobuf:"bytes,17,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Device) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *Device) GetLastHandshakeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshakeTime
	}
	return nil
}

func (x *Device) GetReceiveBytes() int64 {
	if x != nil {
		return x.ReceiveBytes
	}
	return 0
}

func (x *Device) GetTransmitBytes() int64 {
	if x != nil {
		return x.TransmitBytes
	}
	return 0
}

func (x *Device) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Device) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Device) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *Device) GetOwnerProvider() string {
	if x != nil {
		return x.OwnerProvider
	}
	return ""
}

func (x *Device) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *Device) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Device) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Device) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

type AddDeviceReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey          string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey       string                 `protobuf:"bytes,3,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	ManualIpAssignment bool                   `protobuf:"varint,4,opt,name=manual_ip_assignment,json=manualIpAssignment,proto3" json:"manual_ip_assignment,omitempty"`
	ManualIpv4Address  string                 `protobuf:"bytes,5,opt,name=manual_ipv4_address,json=manualIpv4Address,proto3" json:"manual_ipv4_address,omitempty"`
	ManualIpv6Address  string                 `protobuf:"bytes,6,opt,name=manual_ipv6_address,json=manualIpv6Address,proto3" json:"manual_ipv6_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddDeviceReq) Reset() {
	*x = AddDeviceReq{}
	mi := &file_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceReq) ProtoMessage() {}

func (x *AddDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceReq.ProtoReflect.Descriptor instead.
func (*AddDeviceReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{1}
}

func (x *AddDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDeviceReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddDeviceReq) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *AddDeviceReq) GetManualIpAssignment() bool {
	if x != nil {
		return x.ManualIpAssignment
	}
	return false
}

func (x *AddDeviceReq) GetManualIpv4Address() string {
	if x != nil {
		return x.ManualIpv4Address
	}
	return ""
}

func (x *AddDeviceReq) GetManualIpv6Address() string {
	if x != nil {
		return x.ManualIpv6Address
	}
	return ""
}

type RotateDeviceKeyReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// the new pre-shared key, or empty for a device that uses none
	PresharedKey  string `protobuf:"bytes,3,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateDeviceKeyReq) Reset() {
	*x = RotateDeviceKeyReq{}
	mi := &file_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDeviceKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDeviceKeyReq) ProtoMessage() {}

func (x *RotateDeviceKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDeviceKeyReq.ProtoReflect.Descriptor instead.
func (*RotateDeviceKeyReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{2}
}

func (x *RotateDeviceKeyReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RotateDeviceKeyReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RotateDeviceKeyReq) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

type RenameDeviceReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewName string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	// admin only: rename a device of another user
	Owner         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameDeviceReq) Reset() {
	*x = RenameDeviceReq{}
	mi := &file_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameDeviceReq) ProtoMessage() {}

func (x *RenameDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameDeviceReq.ProtoReflect.Descriptor instead.
func (*RenameDeviceReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{3}
}

func (x *RenameDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenameDeviceReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *RenameDeviceReq) GetOwner() *wrapperspb.StringValue {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ListDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesReq) Reset() {
	*x = ListDevicesReq{}
	mi := &file_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesReq) ProtoMessage() {}

func (x *ListDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesReq.ProtoReflect.Descriptor instead.
func (*ListDevicesReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{4}
}

type ListDevicesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Device              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRes) Reset() {
	*x = ListDevicesRes{}
	mi := &file_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRes) ProtoMessage() {}

func (x *ListDevicesRes) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRes.ProtoReflect.Descriptor instead.
func (*ListDevicesRes) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{5}
}

func (x *ListDevicesRes) GetItems() []*Device {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteDeviceReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// admin's may delete a device owned
	// by someone other than the current user
	// if empty, defaults to the current user
	Owner         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceReq) Reset() {
	*x = DeleteDeviceReq{}
	mi := &file_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceReq) ProtoMessage() {}

func (x *DeleteDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceReq.ProtoReflect.Descriptor instead.
func (*DeleteDeviceReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDeviceReq) GetOwner() *wrapperspb.StringValue {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ListAllDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllDevicesReq) Reset() {
	*x = ListAllDevicesReq{}
	mi := &file_devices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllDevicesReq) ProtoMessage() {}

func (x *ListAllDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllDevicesReq.ProtoReflect.Descriptor instead.
func (*ListAllDevicesReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{7}
}

type ListAllDevicesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Device              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllDevicesRes) Reset() {
	*x = ListAllDevicesRes{}
	mi := &file_devices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllDevicesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllDevicesRes) ProtoMessage() {}

func (x *ListAllDevicesRes) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllDevicesRes.ProtoReflect.Descriptor instead.
func (*ListAllDevicesRes) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{8}
}

func (x *ListAllDevicesRes) GetItems() []*Device {
	if x != nil {
		return x.Items
	}
	return nil
}

// SetDeviceRoutesReq replaces the networks behind a device. An empty list
// removes them all, which makes it an ordinary device again.
type SetDeviceRoutesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// if empty, defaults to the current user
	Owner         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Routes        []string                `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceRoutesReq) Reset() {
	*x = SetDeviceRoutesReq{}
	mi := &file_devices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceRoutesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceRoutesReq) ProtoMessage() {}

func (x *SetDeviceRoutesReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceRoutesReq.ProtoReflect.Descriptor instead.
func (*SetDeviceRoutesReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{9}
}

func (x *SetDeviceRoutesReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDeviceRoutesReq) GetOwner() *wrapperspb.StringValue {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SetDeviceRoutesReq) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

// SetDeviceAccessReq changes whether a device may connect. Both changes are
// optional, so one of them can be made without reading and sending back the
// other - two admins working at once then cannot undo each other's change.
type SetDeviceAccessReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// if empty, defaults to the current user
	Owner *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// unset: leave the block as it is
	Disabled *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// unset: leave the expiry as it is. Must be in the future - to end access
	// now, disable the device.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// true: the device's access no longer expires. Takes precedence over
	// expires_at.
	ClearExpiresAt bool `protobuf:"varint,5,opt,name=clear_expires_at,json=clearExpiresAt,proto3" json:"clear_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetDeviceAccessReq) Reset() {
	*x = SetDeviceAccessReq{}
	mi := &file_devices_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceAccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceAccessReq) ProtoMessage() {}

func (x *SetDeviceAccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceAccessReq.ProtoReflect.Descriptor instead.
func (*SetDeviceAccessReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{10}
}

func (x *SetDeviceAccessReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDeviceAccessReq) GetOwner() *wrapperspb.StringValue {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SetDeviceAccessReq) GetDisabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Disabled
	}
	return nil
}

func (x *SetDeviceAccessReq) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SetDeviceAccessReq) GetClearExpiresAt() bool {
	if x != nil {
		return x.ClearExpiresAt
	}
	return false
}

var File_devices_proto protoreflect.FileDescriptor

const file_devices_proto_rawDesc = "" +
	"\n" +
	"\rdevices.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf3\x04\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\tconnected\x18\x06 \x01(\bR\tconnected\x12J\n" +
	"\x13last_handshake_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x11lastHandshakeTime\x12#\n" +
	"\rreceive_bytes\x18\b \x01(\x03R\freceiveBytes\x12%\n" +
	"\x0etransmit_bytes\x18\t \x01(\x03R\rtransmitBytes\x12\x1a\n" +
	"\bendpoint\x18\n" +
	" \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"owner_name\x18\v \x01(\tR\townerName\x12\x1f\n" +
	"\vowner_email\x18\f \x01(\tR\n" +
	"ownerEmail\x12%\n" +
	"\x0eowner_provider\x18\r \x01(\tR\rownerProvider\x12#\n" +
	"\rpreshared_key\x18\x0e \x01(\tR\fpresharedKey\x12\x1a\n" +
	"\bdisabled\x18\x0f \x01(\bR\bdisabled\x129\n" +
	"\n" +
	"expires_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06routes\x18\x11 \x03(\tR\x06routes\"\xf8\x01\n" +
	"\fAddDeviceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12#\n" +
	"\rpreshared_key\x18\x03 \x01(\tR\fpresharedKey\x120\n" +
	"\x14manual_ip_assignment\x18\x04 \x01(\bR\x12manualIpAssignment\x12.\n" +
	"\x13manual_ipv4_address\x18\x05 \x01(\tR\x11manualIpv4Address\x12.\n" +
	"\x13manual_ipv6_address\x18\x06 \x01(\tR\x11manualIpv6Address\"l\n" +
	"\x12RotateDeviceKeyReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12#\n" +
	"\rpreshared_key\x18\x03 \x01(\tR\fpresharedKey\"t\n" +
	"\x0fRenameDeviceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\x122\n" +
	"\x05owner\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05owner\"\x10\n" +
	"\x0eListDevicesReq\"5\n" +
	"\x0eListDevicesRes\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.proto.DeviceR\x05items\"Y\n" +
	"\x0fDeleteDeviceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05owner\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05owner\"\x13\n" +
	"\x11ListAllDevicesReq\"8\n" +
	"\x11ListAllDevicesRes\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.proto.DeviceR\x05items\"t\n" +
	"\x12SetDeviceRoutesReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05owner\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05owner\x12\x16\n" +
	"\x06routes\x18\x03 \x03(\tR\x06routes\"\xf9\x01\n" +
	"\x12SetDeviceAccessReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05owner\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05owner\x126\n" +
	"\bdisabled\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\bdisabled\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12(\n" +
	"\x10clear_expires_at\x18\x05 \x01(\bR\x0eclearExpiresAt2\xfb\x03\n" +
	"\aDevices\x121\n" +
	"\tAddDevice\x12\x13.proto.AddDeviceReq\x1a\r.proto.Device\"\x00\x12=\n" +
	"\vListDevices\x12\x15.proto.ListDevicesReq\x1a\x15.proto.ListDevicesRes\"\x00\x12@\n" +
	"\fDeleteDevice\x12\x16.proto.DeleteDeviceReq\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\fRenameDevice\x12\x16.proto.RenameDeviceReq\x1a\r.proto.Device\"\x00\x12=\n" +
	"\x0fRotateDeviceKey\x12\x19.proto.RotateDeviceKeyReq\x1a\r.proto.Device\"\x00\x12F\n" +
	"\x0eListAllDevices\x12\x18.proto.ListAllDevicesReq\x1a\x18.proto.ListAllDevicesRes\"\x00\x12=\n" +
	"\x0fSetDeviceAccess\x12\x19.proto.SetDeviceAccessReq\x1a\r.proto.Device\"\x00\x12=\n" +
	"\x0fSetDeviceRoutes\x12\x19.proto.SetDeviceRoutesReq\x1a\r.proto.Device\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_devices_proto_rawDescOnce sync.Once
	file_devices_proto_rawDescData []byte
)

func file_devices_proto_rawDescGZIP() []byte {
	file_devices_proto_rawDescOnce.Do(func() {
		file_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devices_proto_rawDesc), len(file_devices_proto_rawDesc)))
	})
	return file_devices_proto_rawDescData
}

var file_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_devices_proto_goTypes = []any{
	(*Device)(nil),                 // 0: proto.Device
	(*AddDeviceReq)(nil),           // 1: proto.AddDeviceReq
	(*RotateDeviceKeyReq)(nil),     // 2: proto.RotateDeviceKeyReq
	(*RenameDeviceReq)(nil),        // 3: proto.RenameDeviceReq
	(*ListDevicesReq)(nil),         // 4: proto.ListDevicesReq
	(*ListDevicesRes)(nil),         // 5: proto.ListDevicesRes
	(*DeleteDeviceReq)(nil),        // 6: proto.DeleteDeviceReq
	(*ListAllDevicesReq)(nil),      // 7: proto.ListAllDevicesReq
	(*ListAllDevicesRes)(nil),      // 8: proto.ListAllDevicesRes
	(*SetDeviceRoutesReq)(nil),     // 9: proto.SetDeviceRoutesReq
	(*SetDeviceAccessReq)(nil),     // 10: proto.SetDeviceAccessReq
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 12: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 13: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),          // 14: google.protobuf.Empty
}
var file_devices_proto_depIdxs = []int32{
	11, // 0: proto.Device.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: proto.Device.last_handshake_time:type_name -> google.protobuf.Timestamp
	11, // 2: proto.Device.expires_at:type_name -> google.protobuf.Timestamp
	12, // 3: proto.RenameDeviceReq.owner:type_name -> google.protobuf.StringValue
	0,  // 4: proto.ListDevicesRes.items:type_name -> proto.Device
	12, // 5: proto.DeleteDeviceReq.owner:type_name -> google.protobuf.StringValue
	0,  // 6: proto.ListAllDevicesRes.items:type_name -> proto.Device
	12, // 7: proto.SetDeviceRoutesReq.owner:type_name -> google.protobuf.StringValue
	12, // 8: proto.SetDeviceAccessReq.owner:type_name -> google.protobuf.StringValue
	13, // 9: proto.SetDeviceAccessReq.disabled:type_name -> google.protobuf.BoolValue
	11, // 10: proto.SetDeviceAccessReq.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 11: proto.Devices.AddDevice:input_type -> proto.AddDeviceReq
	4,  // 12: proto.Devices.ListDevices:input_type -> proto.ListDevicesReq
	6,  // 13: proto.Devices.DeleteDevice:input_type -> proto.DeleteDeviceReq
	3,  // 14: proto.Devices.RenameDevice:input_type -> proto.RenameDeviceReq
	2,  // 15: proto.Devices.RotateDeviceKey:input_type -> proto.RotateDeviceKeyReq
	7,  // 16: proto.Devices.ListAllDevices:input_type -> proto.ListAllDevicesReq
	10, // 17: proto.Devices.SetDeviceAccess:input_type -> proto.SetDeviceAccessReq
	9,  // 18: proto.Devices.SetDeviceRoutes:input_type -> proto.SetDeviceRoutesReq
	0,  // 19: proto.Devices.AddDevice:output_type -> proto.Device
	5,  // 20: proto.Devices.ListDevices:output_type -> proto.ListDevicesRes
	14, // 21: proto.Devices.DeleteDevice:output_type -> google.protobuf.Empty
	0,  // 22: proto.Devices.RenameDevice:output_type -> proto.Device
	0,  // 23: proto.Devices.RotateDeviceKey:output_type -> proto.Device
	8,  // 24: proto.Devices.ListAllDevices:output_type -> proto.ListAllDevicesRes
	0,  // 25: proto.Devices.SetDeviceAccess:output_type -> proto.Device
	0,  // 26: proto.Devices.SetDeviceRoutes:output_type -> proto.Device
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_devices_proto_init() }
func file_devices_proto_init() {
	if File_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devices_proto_rawDesc), len(file_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devices_proto_goTypes,
		DependencyIndexes: file_devices_proto_depIdxs,
		MessageInfos:      file_devices_proto_msgTypes,
	}.Build()
	File_devices_proto = out.File
	file_devices_proto_goTypes = nil
	file_devices_proto_depIdxs = nil
}
