// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type InfoRes struct {
	state                           protoimpl.MessageState  `protogen:"open.v1"`
	PublicKey                       string                  `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Host                            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                            int32                   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MetadataEnabled                 bool                    `protobuf:"varint,5,opt,name=metadata_enabled,json=metadataEnabled,proto3" json:"metadata_enabled,omitempty"`
	IsAdmin                         bool                    `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	AllowedIps                      string                  `protobuf:"bytes,7,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	DnsEnabled                      bool                    `protobuf:"varint,8,opt,name=dns_enabled,json=dnsEnabled,proto3" json:"dns_enabled,omitempty"`
	DnsAddress                      string                  `protobuf:"bytes,9,opt,name=dns_address,json=dnsAddress,proto3" json:"dns_address,omitempty"`
	Filename                        string                  `protobuf:"bytes,10,opt,name=filename,proto3" json:"filename,omitempty"`
	InactiveDeviceDeletionEnabled   bool                    `protobuf:"varint,11,opt,name=inactive_device_deletion_enabled,json=inactiveDeviceDeletionEnabled,proto3" json:"inactive_device_deletion_enabled,omitempty"`
	InactiveDeviceGracePeriod       *durationpb.Duration    `protobuf:"bytes,12,opt,name=inactive_device_grace_period,json=inactiveDeviceGracePeriod,proto3" json:"inactive_device_grace_period,omitempty"`
	ClientConfigDnsServers          string                  `protobuf:"bytes,13,opt,name=client_config_dns_servers,json=clientConfigDnsServers,proto3" json:"client_config_dns_servers,omitempty"`
	ClientConfigDnsSearchDomain     string                  `protobuf:"bytes,14,opt,name=client_config_dns_search_domain,json=clientConfigDnsSearchDomain,proto3" json:"client_config_dns_search_domain,omitempty"`
	ClientConfigMtu                 int32                   `protobuf:"varint,15,opt,name=client_config_mtu,json=clientConfigMtu,proto3" json:"client_config_mtu,omitempty"`
	BuildInfo                       *BuildInfo              `protobuf:"bytes,16,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	Mtu                             int32                   `protobuf:"varint,17,opt,name=mtu,proto3" json:"mtu,omitempty"`
	ClientConfigPersistentKeepalive int32                   `protobuf:"varint,18,opt,name=client_config_persistent_keepalive,json=clientConfigPersistentKeepalive,proto3" json:"client_config_persistent_keepalive,omitempty"`
	ApiTokensEnabled                bool                    `protobuf:"varint,19,opt,name=api_tokens_enabled,json=apiTokensEnabled,proto3" json:"api_tokens_enabled,omitempty"`
	// who is signed in, as their devices name their owner. The UI tells their
	// own row from the others with it - an admin must not be offered an action
	// that would take their own access away mid-click.
	Subject string `protobuf:"bytes,20,opt,name=subject,proto3" json:"subject,omitempty"`
	// whether this session can change its own password: the built-in sign-in
	// keeps it here, an identity provider keeps it itself
	PasswordChangeEnabled bool `protobuf:"varint,21,opt,name=password_change_enabled,json=passwordChangeEnabled,proto3" json:"password_change_enabled,omitempty"`
	// whether this session's account is asked for a second factor
	TwoFactorEnabled bool `protobuf:"varint,22,opt,name=two_factor_enabled,json=twoFactorEnabled,proto3" json:"two_factor_enabled,omitempty"`
	// how many recovery codes it has left, so the UI can say when they run low
	RecoveryCodesLeft int32 `protobuf:"varint,23,opt,name=recovery_codes_left,json=recoveryCodesLeft,proto3" json:"recovery_codes_left,omitempty"`
	// how many passkeys this session's account has registered
	Passkeys      int32 `protobuf:"varint,24,opt,name=passkeys,proto3" json:"passkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRes) Reset() {
	*x = InfoRes{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRes) ProtoMessage() {}

func (x *InfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRes.ProtoReflect.Descriptor instead.
func (*InfoRes) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *InfoRes) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InfoRes) GetHost() *wrapperspb.StringValue {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *InfoRes) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InfoRes) GetMetadataEnabled() bool {
	if x != nil {
		return x.MetadataEnabled
	}
	return false
}

func (x *InfoRes) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *InfoRes) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *InfoRes) GetDnsEnabled() bool {
	if x != nil {
		return x.DnsEnabled
	}
	return false
}

func (x *InfoRes) GetDnsAddress() string {
	if x != nil {
		return x.DnsAddress
	}
	return ""
}

func (x *InfoRes) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InfoRes) GetInactiveDeviceDeletionEnabled() bool {
	if x != nil {
		return x.InactiveDeviceDeletionEnabled
	}
	return false
}

func (x *InfoRes) GetInactiveDeviceGracePeriod() *durationpb.Duration {
	if x != nil {
		return x.InactiveDeviceGracePeriod
	}
	return nil
}

func (x *InfoRes) GetClientConfigDnsServers() string {
	if x != nil {
		return x.ClientConfigDnsServers
	}
	return ""
}

func (x *InfoRes) GetClientConfigDnsSearchDomain() string {
	if x != nil {
		return x.ClientConfigDnsSearchDomain
	}
	return ""
}

func (x *InfoRes) GetClientConfigMtu() int32 {
	if x != nil {
		return x.ClientConfigMtu
	}
	return 0
}

func (x *InfoRes) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *InfoRes) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *InfoRes) GetClientConfigPersistentKeepalive() int32 {
	if x != nil {
		return x.ClientConfigPersistentKeepalive
	}
	return 0
}

func (x *InfoRes) GetApiTokensEnabled() bool {
	if x != nil {
		return x.ApiTokensEnabled
	}
	return false
}

func (x *InfoRes) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InfoRes) GetPasswordChangeEnabled() bool {
	if x != nil {
		return x.PasswordChangeEnabled
	}
	return false
}

func (x *InfoRes) GetTwoFactorEnabled() bool {
	if x != nil {
		return x.TwoFactorEnabled
	}
	return false
}

func (x *InfoRes) GetRecoveryCodesLeft() int32 {
	if x != nil {
		return x.RecoveryCodesLeft
	}
	return 0
}

func (x *InfoRes) GetPasskeys() int32 {
	if x != nil {
		return x.Passkeys
	}
	return 0
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0fbuildinfo.proto\"\t\n" +
	"\aInfoReq\"\xa2\b\n" +
	"\aInfoRes\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x120\n" +
	"\x04host\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12)\n" +
	"\x10metadata_enabled\x18\x05 \x01(\bR\x0fmetadataEnabled\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\x12\x1f\n" +
	"\vallowed_ips\x18\a \x01(\tR\n" +
	"allowedIps\x12\x1f\n" +
	"\vdns_enabled\x18\b \x01(\bR\n" +
	"dnsEnabled\x12\x1f\n" +
	"\vdns_address\x18\t \x01(\tR\n" +
	"dnsAddress\x12\x1a\n" +
	"\bfilename\x18\n" +
	" \x01(\tR\bfilename\x12G\n" +
	" inactive_device_deletion_enabled\x18\v \x01(\bR\x1dinactiveDeviceDeletionEnabled\x12Z\n" +
	"\x1cinactive_device_grace_period\x18\f \x01(\v2\x19.google.protobuf.DurationR\x19inactiveDeviceGracePeriod\x129\n" +
	"\x19client_config_dns_servers\x18\r \x01(\tR\x16clientConfigDnsServers\x12D\n" +
	"\x1fclient_config_dns_search_domain\x18\x0e \x01(\tR\x1bclientConfigDnsSearchDomain\x12*\n" +
	"\x11client_config_mtu\x18\x0f \x01(\x05R\x0fclientConfigMtu\x12/\n" +
	"\n" +
	"build_info\x18\x10 \x01(\v2\x10.proto.BuildInfoR\tbuildInfo\x12\x10\n" +
	"\x03mtu\x18\x11 \x01(\x05R\x03mtu\x12K\n" +
	"\"client_config_persistent_keepalive\x18\x12 \x01(\x05R\x1fclientConfigPersistentKeepalive\x12,\n" +
	"\x12api_tokens_enabled\x18\x13 \x01(\bR\x10apiTokensEnabled\x12\x18\n" +
	"\asubject\x18\x14 \x01(\tR\asubject\x126\n" +
	"\x17password_change_enabled\x18\x15 \x01(\bR\x15passwordChangeEnabled\x12,\n" +
	"\x12two_factor_enabled\x18\x16 \x01(\bR\x10twoFactorEnabled\x12.\n" +
	"\x13recovery_codes_left\x18\x17 \x01(\x05R\x11recoveryCodesLeft\x12\x1a\n" +
	"\bpasskeys\x18\x18 \x01(\x05R\bpasskeysJ\x04\b\x04\x10\x05R\vhost_vpn_ip22\n" +
	"\x06Server\x12(\n" +
	"\x04Info\x12\x0e.proto.InfoReq\x1a\x0e.proto.InfoRes\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_proto_goTypes = []any{
	(*InfoReq)(nil),                // 0: proto.InfoReq
	(*InfoRes)(nil),                // 1: proto.InfoRes
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
	(*durationpb.Duration)(nil),    // 3: google.protobuf.Duration
	(*BuildInfo)(nil),              // 4: proto.BuildInfo
}
var file_server_proto_depIdxs = []int32{
	2, // 0: proto.InfoRes.host:type_name -> google.protobuf.StringValue
	3, // 1: proto.InfoRes.inactive_device_grace_period:type_name -> google.protobuf.Duration
	4, // 2: proto.InfoRes.build_info:type_name -> proto.BuildInfo
	0, // 3: proto.Server.Info:input_type -> proto.InfoReq
	1, // 4: proto.Server.Info:output_type -> proto.InfoRes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_buildinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
