// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0--rc3
// source: server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type InfoRes struct {
	state                           protoimpl.MessageState  `protogen:"open.v1"`
	PublicKey                       string                  `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Host                            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                            int32                   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	HostVpnIp                       string                  `protobuf:"bytes,4,opt,name=host_vpn_ip,json=hostVpnIp,proto3" json:"host_vpn_ip,omitempty"`
	MetadataEnabled                 bool                    `protobuf:"varint,5,opt,name=metadata_enabled,json=metadataEnabled,proto3" json:"metadata_enabled,omitempty"`
	IsAdmin                         bool                    `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	AllowedIps                      string                  `protobuf:"bytes,7,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	DnsEnabled                      bool                    `protobuf:"varint,8,opt,name=dns_enabled,json=dnsEnabled,proto3" json:"dns_enabled,omitempty"`
	DnsAddress                      string                  `protobuf:"bytes,9,opt,name=dns_address,json=dnsAddress,proto3" json:"dns_address,omitempty"`
	Filename                        string                  `protobuf:"bytes,10,opt,name=filename,proto3" json:"filename,omitempty"`
	InactiveDeviceDeletionEnabled   bool                    `protobuf:"varint,11,opt,name=inactive_device_deletion_enabled,json=inactiveDeviceDeletionEnabled,proto3" json:"inactive_device_deletion_enabled,omitempty"`
	InactiveDeviceGracePeriod       *durationpb.Duration    `protobuf:"bytes,12,opt,name=inactive_device_grace_period,json=inactiveDeviceGracePeriod,proto3" json:"inactive_device_grace_period,omitempty"`
	ClientConfigDnsServers          string                  `protobuf:"bytes,13,opt,name=client_config_dns_servers,json=clientConfigDnsServers,proto3" json:"client_config_dns_servers,omitempty"`
	ClientConfigDnsSearchDomain     string                  `protobuf:"bytes,14,opt,name=client_config_dns_search_domain,json=clientConfigDnsSearchDomain,proto3" json:"client_config_dns_search_domain,omitempty"`
	ClientConfigMtu                 int32                   `protobuf:"varint,15,opt,name=client_config_mtu,json=clientConfigMtu,proto3" json:"client_config_mtu,omitempty"`
	BuildInfo                       *BuildInfo              `protobuf:"bytes,16,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	Mtu                             int32                   `protobuf:"varint,17,opt,name=mtu,proto3" json:"mtu,omitempty"`
	ClientConfigPersistentKeepalive int32                   `protobuf:"varint,18,opt,name=client_config_persistent_keepalive,json=clientConfigPersistentKeepalive,proto3" json:"client_config_persistent_keepalive,omitempty"`
	AmneziaJc                       uint32                  `protobuf:"varint,19,opt,name=amnezia_jc,json=amneziaJc,proto3" json:"amnezia_jc,omitempty"`
	AmneziaJmin                     uint32                  `protobuf:"varint,20,opt,name=amnezia_jmin,json=amneziaJmin,proto3" json:"amnezia_jmin,omitempty"`
	AmneziaJmax                     uint32                  `protobuf:"varint,21,opt,name=amnezia_jmax,json=amneziaJmax,proto3" json:"amnezia_jmax,omitempty"`
	AmneziaS1                       uint32                  `protobuf:"varint,22,opt,name=amnezia_s1,json=amneziaS1,proto3" json:"amnezia_s1,omitempty"`
	AmneziaS2                       uint32                  `protobuf:"varint,23,opt,name=amnezia_s2,json=amneziaS2,proto3" json:"amnezia_s2,omitempty"`
	AmneziaS3                       uint32                  `protobuf:"varint,24,opt,name=amnezia_s3,json=amneziaS3,proto3" json:"amnezia_s3,omitempty"`
	AmneziaS4                       uint32                  `protobuf:"varint,25,opt,name=amnezia_s4,json=amneziaS4,proto3" json:"amnezia_s4,omitempty"`
	AmneziaH1                       string                  `protobuf:"bytes,26,opt,name=amnezia_h1,json=amneziaH1,proto3" json:"amnezia_h1,omitempty"`
	AmneziaH2                       string                  `protobuf:"bytes,27,opt,name=amnezia_h2,json=amneziaH2,proto3" json:"amnezia_h2,omitempty"`
	AmneziaH3                       string                  `protobuf:"bytes,28,opt,name=amnezia_h3,json=amneziaH3,proto3" json:"amnezia_h3,omitempty"`
	AmneziaH4                       string                  `protobuf:"bytes,29,opt,name=amnezia_h4,json=amneziaH4,proto3" json:"amnezia_h4,omitempty"`
	AmneziaI1                       string                  `protobuf:"bytes,30,opt,name=amnezia_i1,json=amneziaI1,proto3" json:"amnezia_i1,omitempty"`
	AmneziaI2                       string                  `protobuf:"bytes,31,opt,name=amnezia_i2,json=amneziaI2,proto3" json:"amnezia_i2,omitempty"`
	AmneziaI3                       string                  `protobuf:"bytes,32,opt,name=amnezia_i3,json=amneziaI3,proto3" json:"amnezia_i3,omitempty"`
	AmneziaI4                       string                  `protobuf:"bytes,33,opt,name=amnezia_i4,json=amneziaI4,proto3" json:"amnezia_i4,omitempty"`
	AmneziaI5                       string                  `protobuf:"bytes,34,opt,name=amnezia_i5,json=amneziaI5,proto3" json:"amnezia_i5,omitempty"`
	AmneziaContentPaddingAddition   string                  `protobuf:"bytes,35,opt,name=amnezia_content_padding_addition,json=amneziaContentPaddingAddition,proto3" json:"amnezia_content_padding_addition,omitempty"`
	AmneziaRekeyAfterTime           string                  `protobuf:"bytes,36,opt,name=amnezia_rekey_after_time,json=amneziaRekeyAfterTime,proto3" json:"amnezia_rekey_after_time,omitempty"`
	AmneziaRekeyTimeout             string                  `protobuf:"bytes,37,opt,name=amnezia_rekey_timeout,json=amneziaRekeyTimeout,proto3" json:"amnezia_rekey_timeout,omitempty"`
	AmneziaRejectAfterTime          string                  `protobuf:"bytes,38,opt,name=amnezia_reject_after_time,json=amneziaRejectAfterTime,proto3" json:"amnezia_reject_after_time,omitempty"`
	AmneziaKeepaliveTimeout         string                  `protobuf:"bytes,39,opt,name=amnezia_keepalive_timeout,json=amneziaKeepaliveTimeout,proto3" json:"amnezia_keepalive_timeout,omitempty"`
	AmneziaMaxHandshakeAttempts     string                  `protobuf:"bytes,40,opt,name=amnezia_max_handshake_attempts,json=amneziaMaxHandshakeAttempts,proto3" json:"amnezia_max_handshake_attempts,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *InfoRes) Reset() {
	*x = InfoRes{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRes) ProtoMessage() {}

func (x *InfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRes.ProtoReflect.Descriptor instead.
func (*InfoRes) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *InfoRes) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InfoRes) GetHost() *wrapperspb.StringValue {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *InfoRes) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InfoRes) GetHostVpnIp() string {
	if x != nil {
		return x.HostVpnIp
	}
	return ""
}

func (x *InfoRes) GetMetadataEnabled() bool {
	if x != nil {
		return x.MetadataEnabled
	}
	return false
}

func (x *InfoRes) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *InfoRes) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *InfoRes) GetDnsEnabled() bool {
	if x != nil {
		return x.DnsEnabled
	}
	return false
}

func (x *InfoRes) GetDnsAddress() string {
	if x != nil {
		return x.DnsAddress
	}
	return ""
}

func (x *InfoRes) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InfoRes) GetInactiveDeviceDeletionEnabled() bool {
	if x != nil {
		return x.InactiveDeviceDeletionEnabled
	}
	return false
}

func (x *InfoRes) GetInactiveDeviceGracePeriod() *durationpb.Duration {
	if x != nil {
		return x.InactiveDeviceGracePeriod
	}
	return nil
}

func (x *InfoRes) GetClientConfigDnsServers() string {
	if x != nil {
		return x.ClientConfigDnsServers
	}
	return ""
}

func (x *InfoRes) GetClientConfigDnsSearchDomain() string {
	if x != nil {
		return x.ClientConfigDnsSearchDomain
	}
	return ""
}

func (x *InfoRes) GetClientConfigMtu() int32 {
	if x != nil {
		return x.ClientConfigMtu
	}
	return 0
}

func (x *InfoRes) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *InfoRes) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *InfoRes) GetClientConfigPersistentKeepalive() int32 {
	if x != nil {
		return x.ClientConfigPersistentKeepalive
	}
	return 0
}

func (x *InfoRes) GetAmneziaJc() uint32 {
	if x != nil {
		return x.AmneziaJc
	}
	return 0
}

func (x *InfoRes) GetAmneziaJmin() uint32 {
	if x != nil {
		return x.AmneziaJmin
	}
	return 0
}

func (x *InfoRes) GetAmneziaJmax() uint32 {
	if x != nil {
		return x.AmneziaJmax
	}
	return 0
}

func (x *InfoRes) GetAmneziaS1() uint32 {
	if x != nil {
		return x.AmneziaS1
	}
	return 0
}

func (x *InfoRes) GetAmneziaS2() uint32 {
	if x != nil {
		return x.AmneziaS2
	}
	return 0
}

func (x *InfoRes) GetAmneziaS3() uint32 {
	if x != nil {
		return x.AmneziaS3
	}
	return 0
}

func (x *InfoRes) GetAmneziaS4() uint32 {
	if x != nil {
		return x.AmneziaS4
	}
	return 0
}

func (x *InfoRes) GetAmneziaH1() string {
	if x != nil {
		return x.AmneziaH1
	}
	return ""
}

func (x *InfoRes) GetAmneziaH2() string {
	if x != nil {
		return x.AmneziaH2
	}
	return ""
}

func (x *InfoRes) GetAmneziaH3() string {
	if x != nil {
		return x.AmneziaH3
	}
	return ""
}

func (x *InfoRes) GetAmneziaH4() string {
	if x != nil {
		return x.AmneziaH4
	}
	return ""
}

func (x *InfoRes) GetAmneziaI1() string {
	if x != nil {
		return x.AmneziaI1
	}
	return ""
}

func (x *InfoRes) GetAmneziaI2() string {
	if x != nil {
		return x.AmneziaI2
	}
	return ""
}

func (x *InfoRes) GetAmneziaI3() string {
	if x != nil {
		return x.AmneziaI3
	}
	return ""
}

func (x *InfoRes) GetAmneziaI4() string {
	if x != nil {
		return x.AmneziaI4
	}
	return ""
}

func (x *InfoRes) GetAmneziaI5() string {
	if x != nil {
		return x.AmneziaI5
	}
	return ""
}

func (x *InfoRes) GetAmneziaContentPaddingAddition() string {
	if x != nil {
		return x.AmneziaContentPaddingAddition
	}
	return ""
}

func (x *InfoRes) GetAmneziaRekeyAfterTime() string {
	if x != nil {
		return x.AmneziaRekeyAfterTime
	}
	return ""
}

func (x *InfoRes) GetAmneziaRekeyTimeout() string {
	if x != nil {
		return x.AmneziaRekeyTimeout
	}
	return ""
}

func (x *InfoRes) GetAmneziaRejectAfterTime() string {
	if x != nil {
		return x.AmneziaRejectAfterTime
	}
	return ""
}

func (x *InfoRes) GetAmneziaKeepaliveTimeout() string {
	if x != nil {
		return x.AmneziaKeepaliveTimeout
	}
	return ""
}

func (x *InfoRes) GetAmneziaMaxHandshakeAttempts() string {
	if x != nil {
		return x.AmneziaMaxHandshakeAttempts
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0fbuildinfo.proto\"\t\n" +
	"\aInfoReq\"\x9f\r\n" +
	"\aInfoRes\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x120\n" +
	"\x04host\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1e\n" +
	"\vhost_vpn_ip\x18\x04 \x01(\tR\thostVpnIp\x12)\n" +
	"\x10metadata_enabled\x18\x05 \x01(\bR\x0fmetadataEnabled\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\x12\x1f\n" +
	"\vallowed_ips\x18\a \x01(\tR\n" +
	"allowedIps\x12\x1f\n" +
	"\vdns_enabled\x18\b \x01(\bR\n" +
	"dnsEnabled\x12\x1f\n" +
	"\vdns_address\x18\t \x01(\tR\n" +
	"dnsAddress\x12\x1a\n" +
	"\bfilename\x18\n" +
	" \x01(\tR\bfilename\x12G\n" +
	" inactive_device_deletion_enabled\x18\v \x01(\bR\x1dinactiveDeviceDeletionEnabled\x12Z\n" +
	"\x1cinactive_device_grace_period\x18\f \x01(\v2\x19.google.protobuf.DurationR\x19inactiveDeviceGracePeriod\x129\n" +
	"\x19client_config_dns_servers\x18\r \x01(\tR\x16clientConfigDnsServers\x12D\n" +
	"\x1fclient_config_dns_search_domain\x18\x0e \x01(\tR\x1bclientConfigDnsSearchDomain\x12*\n" +
	"\x11client_config_mtu\x18\x0f \x01(\x05R\x0fclientConfigMtu\x12/\n" +
	"\n" +
	"build_info\x18\x10 \x01(\v2\x10.proto.BuildInfoR\tbuildInfo\x12\x10\n" +
	"\x03mtu\x18\x11 \x01(\x05R\x03mtu\x12K\n" +
	"\"client_config_persistent_keepalive\x18\x12 \x01(\x05R\x1fclientConfigPersistentKeepalive\x12\x1d\n" +
	"\n" +
	"amnezia_jc\x18\x13 \x01(\rR\tamneziaJc\x12!\n" +
	"\famnezia_jmin\x18\x14 \x01(\rR\vamneziaJmin\x12!\n" +
	"\famnezia_jmax\x18\x15 \x01(\rR\vamneziaJmax\x12\x1d\n" +
	"\n" +
	"amnezia_s1\x18\x16 \x01(\rR\tamneziaS1\x12\x1d\n" +
	"\n" +
	"amnezia_s2\x18\x17 \x01(\rR\tamneziaS2\x12\x1d\n" +
	"\n" +
	"amnezia_s3\x18\x18 \x01(\rR\tamneziaS3\x12\x1d\n" +
	"\n" +
	"amnezia_s4\x18\x19 \x01(\rR\tamneziaS4\x12\x1d\n" +
	"\n" +
	"amnezia_h1\x18\x1a \x01(\tR\tamneziaH1\x12\x1d\n" +
	"\n" +
	"amnezia_h2\x18\x1b \x01(\tR\tamneziaH2\x12\x1d\n" +
	"\n" +
	"amnezia_h3\x18\x1c \x01(\tR\tamneziaH3\x12\x1d\n" +
	"\n" +
	"amnezia_h4\x18\x1d \x01(\tR\tamneziaH4\x12\x1d\n" +
	"\n" +
	"amnezia_i1\x18\x1e \x01(\tR\tamneziaI1\x12\x1d\n" +
	"\n" +
	"amnezia_i2\x18\x1f \x01(\tR\tamneziaI2\x12\x1d\n" +
	"\n" +
	"amnezia_i3\x18  \x01(\tR\tamneziaI3\x12\x1d\n" +
	"\n" +
	"amnezia_i4\x18! \x01(\tR\tamneziaI4\x12\x1d\n" +
	"\n" +
	"amnezia_i5\x18\" \x01(\tR\tamneziaI5\x12G\n" +
	" amnezia_content_padding_addition\x18# \x01(\tR\x1damneziaContentPaddingAddition\x127\n" +
	"\x18amnezia_rekey_after_time\x18$ \x01(\tR\x15amneziaRekeyAfterTime\x122\n" +
	"\x15amnezia_rekey_timeout\x18% \x01(\tR\x13amneziaRekeyTimeout\x129\n" +
	"\x19amnezia_reject_after_time\x18& \x01(\tR\x16amneziaRejectAfterTime\x12:\n" +
	"\x19amnezia_keepalive_timeout\x18' \x01(\tR\x17amneziaKeepaliveTimeout\x12C\n" +
	"\x1eamnezia_max_handshake_attempts\x18( \x01(\tR\x1bamneziaMaxHandshakeAttempts22\n" +
	"\x06Server\x12(\n" +
	"\x04Info\x12\x0e.proto.InfoReq\x1a\x0e.proto.InfoRes\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_proto_goTypes = []any{
	(*InfoReq)(nil),                // 0: proto.InfoReq
	(*InfoRes)(nil),                // 1: proto.InfoRes
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
	(*durationpb.Duration)(nil),    // 3: google.protobuf.Duration
	(*BuildInfo)(nil),              // 4: proto.BuildInfo
}
var file_server_proto_depIdxs = []int32{
	2, // 0: proto.InfoRes.host:type_name -> google.protobuf.StringValue
	3, // 1: proto.InfoRes.inactive_device_grace_period:type_name -> google.protobuf.Duration
	4, // 2: proto.InfoRes.build_info:type_name -> proto.BuildInfo
	0, // 3: proto.Server.Info:input_type -> proto.InfoReq
	1, // 4: proto.Server.Info:output_type -> proto.InfoRes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_buildinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
