// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: sessions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// what the browser said about itself when the session started
	UserAgent string `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// the address it came from, which behind a reverse proxy is the proxy
	RemoteAddr string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeenAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// whether this is the session the request was made with
	Current       bool `protobuf:"varint,7,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Session) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type ListSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsReq) Reset() {
	*x = ListSessionsReq{}
	mi := &file_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsReq) ProtoMessage() {}

func (x *ListSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsReq.ProtoReflect.Descriptor instead.
func (*ListSessionsReq) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{1}
}

type ListSessionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Session             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRes) Reset() {
	*x = ListSessionsRes{}
	mi := &file_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRes) ProtoMessage() {}

func (x *ListSessionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRes.ProtoReflect.Descriptor instead.
func (*ListSessionsRes) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRes) GetItems() []*Session {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionReq) Reset() {
	*x = DeleteSessionReq{}
	mi := &file_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionReq) ProtoMessage() {}

func (x *DeleteSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionReq.ProtoReflect.Descriptor instead.
func (*DeleteSessionReq) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSessionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOtherSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOtherSessionsReq) Reset() {
	*x = DeleteOtherSessionsReq{}
	mi := &file_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOtherSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOtherSessionsReq) ProtoMessage() {}

func (x *DeleteOtherSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOtherSessionsReq.ProtoReflect.Descriptor instead.
func (*DeleteOtherSessionsReq) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{4}
}

type DeleteOtherSessionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ended         int32                  `protobuf:"varint,1,opt,name=ended,proto3" json:"ended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOtherSessionsRes) Reset() {
	*x = DeleteOtherSessionsRes{}
	mi := &file_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOtherSessionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOtherSessionsRes) ProtoMessage() {}

func (x *DeleteOtherSessionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOtherSessionsRes.ProtoReflect.Descriptor instead.
func (*DeleteOtherSessionsRes) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteOtherSessionsRes) GetEnded() int32 {
	if x != nil {
		return x.Ended
	}
	return 0
}

var File_sessions_proto protoreflect.FileDescriptor

const file_sessions_proto_rawDesc = "" +
	"\n" +
	"\x0esessions.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa7\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\acurrent\x18\a \x01(\bR\acurrent\"\x11\n" +
	"\x0fListSessionsReq\"7\n" +
	"\x0fListSessionsRes\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.proto.SessionR\x05items\"\"\n" +
	"\x10DeleteSessionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteOtherSessionsReq\".\n" +
	"\x16DeleteOtherSessionsRes\x12\x14\n" +
	"\x05ended\x18\x01 \x01(\x05R\x05ended2\xe7\x01\n" +
	"\bSessions\x12@\n" +
	"\fListSessions\x12\x16.proto.ListSessionsReq\x1a\x16.proto.ListSessionsRes\"\x00\x12B\n" +
	"\rDeleteSession\x12\x17.proto.DeleteSessionReq\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x13DeleteOtherSessions\x12\x1d.proto.DeleteOtherSessionsReq\x1a\x1d.proto.DeleteOtherSessionsRes\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_sessions_proto_rawDescOnce sync.Once
	file_sessions_proto_rawDescData []byte
)

func file_sessions_proto_rawDescGZIP() []byte {
	file_sessions_proto_rawDescOnce.Do(func() {
		file_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)))
	})
	return file_sessions_proto_rawDescData
}

var file_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sessions_proto_goTypes = []any{
	(*Session)(nil),                // 0: proto.Session
	(*ListSessionsReq)(nil),        // 1: proto.ListSessionsReq
	(*ListSessionsRes)(nil),        // 2: proto.ListSessionsRes
	(*DeleteSessionReq)(nil),       // 3: proto.DeleteSessionReq
	(*DeleteOtherSessionsReq)(nil), // 4: proto.DeleteOtherSessionsReq
	(*DeleteOtherSessionsRes)(nil), // 5: proto.DeleteOtherSessionsRes
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_sessions_proto_depIdxs = []int32{
	6, // 0: proto.Session.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: proto.Session.last_seen_at:type_name -> google.protobuf.Timestamp
	6, // 2: proto.Session.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: proto.ListSessionsRes.items:type_name -> proto.Session
	1, // 4: proto.Sessions.ListSessions:input_type -> proto.ListSessionsReq
	3, // 5: proto.Sessions.DeleteSession:input_type -> proto.DeleteSessionReq
	4, // 6: proto.Sessions.DeleteOtherSessions:input_type -> proto.DeleteOtherSessionsReq
	2, // 7: proto.Sessions.ListSessions:output_type -> proto.ListSessionsRes
	7, // 8: proto.Sessions.DeleteSession:output_type -> google.protobuf.Empty
	5, // 9: proto.Sessions.DeleteOtherSessions:output_type -> proto.DeleteOtherSessionsRes
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sessions_proto_init() }
func file_sessions_proto_init() {
	if File_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessions_proto_goTypes,
		DependencyIndexes: file_sessions_proto_depIdxs,
		MessageInfos:      file_sessions_proto_msgTypes,
	}.Build()
	File_sessions_proto = out.File
	file_sessions_proto_goTypes = nil
	file_sessions_proto_depIdxs = nil
}
