// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: tokens.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner     string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerName string                 `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// unset: the token does not expire
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// unset: the token was never used
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Token) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Token) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Token) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Token) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type CreateTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// unset: the token does not expire
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenReq) Reset() {
	*x = CreateTokenReq{}
	mi := &file_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenReq) ProtoMessage() {}

func (x *CreateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenReq.ProtoReflect.Descriptor instead.
func (*CreateTokenReq) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokenReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenReq) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateTokenRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The token itself. It is not stored and cannot be shown again.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRes) Reset() {
	*x = CreateTokenRes{}
	mi := &file_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRes) ProtoMessage() {}

func (x *CreateTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRes.ProtoReflect.Descriptor instead.
func (*CreateTokenRes) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTokenRes) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateTokenRes) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ListTokensReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensReq) Reset() {
	*x = ListTokensReq{}
	mi := &file_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensReq) ProtoMessage() {}

func (x *ListTokensReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensReq.ProtoReflect.Descriptor instead.
func (*ListTokensReq) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{3}
}

type ListTokensRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Token               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRes) Reset() {
	*x = ListTokensRes{}
	mi := &file_tokens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRes) ProtoMessage() {}

func (x *ListTokensRes) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRes.ProtoReflect.Descriptor instead.
func (*ListTokensRes) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *ListTokensRes) GetItems() []*Token {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenReq) Reset() {
	*x = DeleteTokenReq{}
	mi := &file_tokens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenReq) ProtoMessage() {}

func (x *DeleteTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenReq.ProtoReflect.Descriptor instead.
func (*DeleteTokenReq) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTokenReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAllTokensReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllTokensReq) Reset() {
	*x = ListAllTokensReq{}
	mi := &file_tokens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllTokensReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllTokensReq) ProtoMessage() {}

func (x *ListAllTokensReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllTokensReq.ProtoReflect.Descriptor instead.
func (*ListAllTokensReq) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{6}
}

type ListAllTokensRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Token               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllTokensRes) Reset() {
	*x = ListAllTokensRes{}
	mi := &file_tokens_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllTokensRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllTokensRes) ProtoMessage() {}

func (x *ListAllTokensRes) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllTokensRes.ProtoReflect.Descriptor instead.
func (*ListAllTokensRes) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllTokensRes) GetItems() []*Token {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_tokens_proto protoreflect.FileDescriptor

const file_tokens_proto_rawDesc = "" +
	"\n" +
	"\ftokens.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x02\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"_\n" +
	"\x0eCreateTokenReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"L\n" +
	"\x0eCreateTokenRes\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.proto.TokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x0f\n" +
	"\rListTokensReq\"3\n" +
	"\rListTokensRes\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.proto.TokenR\x05items\" \n" +
	"\x0eDeleteTokenReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ListAllTokensReq\"6\n" +
	"\x10ListAllTokensRes\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.proto.TokenR\x05items2\x88\x02\n" +
	"\x06Tokens\x12=\n" +
	"\vCreateToken\x12\x15.proto.CreateTokenReq\x1a\x15.proto.CreateTokenRes\"\x00\x12:\n" +
	"\n" +
	"ListTokens\x12\x14.proto.ListTokensReq\x1a\x14.proto.ListTokensRes\"\x00\x12>\n" +
	"\vDeleteToken\x12\x15.proto.DeleteTokenReq\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\rListAllTokens\x12\x17.proto.ListAllTokensReq\x1a\x17.proto.ListAllTokensRes\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_tokens_proto_rawDescOnce sync.Once
	file_tokens_proto_rawDescData []byte
)

func file_tokens_proto_rawDescGZIP() []byte {
	file_tokens_proto_rawDescOnce.Do(func() {
		file_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokens_proto_rawDesc), len(file_tokens_proto_rawDesc)))
	})
	return file_tokens_proto_rawDescData
}

var file_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tokens_proto_goTypes = []any{
	(*Token)(nil),                 // 0: proto.Token
	(*CreateTokenReq)(nil),        // 1: proto.CreateTokenReq
	(*CreateTokenRes)(nil),        // 2: proto.CreateTokenRes
	(*ListTokensReq)(nil),         // 3: proto.ListTokensReq
	(*ListTokensRes)(nil),         // 4: proto.ListTokensRes
	(*DeleteTokenReq)(nil),        // 5: proto.DeleteTokenReq
	(*ListAllTokensReq)(nil),      // 6: proto.ListAllTokensReq
	(*ListAllTokensRes)(nil),      // 7: proto.ListAllTokensRes
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_tokens_proto_depIdxs = []int32{
	8,  // 0: proto.Token.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: proto.Token.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 2: proto.Token.last_used_at:type_name -> google.protobuf.Timestamp
	8,  // 3: proto.CreateTokenReq.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: proto.CreateTokenRes.token:type_name -> proto.Token
	0,  // 5: proto.ListTokensRes.items:type_name -> proto.Token
	0,  // 6: proto.ListAllTokensRes.items:type_name -> proto.Token
	1,  // 7: proto.Tokens.CreateToken:input_type -> proto.CreateTokenReq
	3,  // 8: proto.Tokens.ListTokens:input_type -> proto.ListTokensReq
	5,  // 9: proto.Tokens.DeleteToken:input_type -> proto.DeleteTokenReq
	6,  // 10: proto.Tokens.ListAllTokens:input_type -> proto.ListAllTokensReq
	2,  // 11: proto.Tokens.CreateToken:output_type -> proto.CreateTokenRes
	4,  // 12: proto.Tokens.ListTokens:output_type -> proto.ListTokensRes
	9,  // 13: proto.Tokens.DeleteToken:output_type -> google.protobuf.Empty
	7,  // 14: proto.Tokens.ListAllTokens:output_type -> proto.ListAllTokensRes
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tokens_proto_init() }
func file_tokens_proto_init() {
	if File_tokens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokens_proto_rawDesc), len(file_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokens_proto_goTypes,
		DependencyIndexes: file_tokens_proto_depIdxs,
		MessageInfos:      file_tokens_proto_msgTypes,
	}.Build()
	File_tokens_proto = out.File
	file_tokens_proto_goTypes = nil
	file_tokens_proto_depIdxs = nil
}
